/**
 * Silsilah Adam → Yesus mengikuti Lukas 3:23–38 (urutan kronologis).
 * Catatan: Matius 1 menempuh jalur lain dari Daud melalui Salomo.
 */

export type GenealogyEraId =
  | "penciptaan"
  | "air-bah"
  | "patriarkh"
  | "menuju-daud"
  | "kerajaan"
  | "pembuangan"
  | "menunggu"
  | "messias";

export type GenealogyPerson = {
  id: string;
  name: string;
  alsoCalled?: string[];
  /** Generasi keberapa dari Adam (Adam = 1) */
  generation: number;
  era: GenealogyEraId;
  note: string;
  /** Tokoh di katalog /baca/tokoh jika ada */
  characterSlug?: string;
  /** Referensi ayat terkait */
  passage?: string;
  verse?: number;
  reference?: string;
  featured?: boolean;
};

export type GenealogyEra = {
  id: GenealogyEraId;
  label: string;
  summary: string;
  accent: string;
};

export const GENEALOGY_ERAS: GenealogyEra[] = [
  {
    id: "penciptaan",
    label: "Penciptaan",
    summary: "Dari Adam hingga generasi sebelum air bah.",
    accent: "#5b7c5a",
  },
  {
    id: "air-bah",
    label: "Air bah & bangsa-bangsa",
    summary: "Nuh, Sem, dan garis menuju Terah.",
    accent: "#3d6f8c",
  },
  {
    id: "patriarkh",
    label: "Patriarkh",
    summary: "Abraham, Ishak, Yakub, dan Yehuda.",
    accent: "#b45309",
  },
  {
    id: "menuju-daud",
    label: "Menuju Daud",
    summary: "Dari Peres hingga Isai di Betlehem.",
    accent: "#7c5c3a",
  },
  {
    id: "kerajaan",
    label: "Garis Daud",
    summary: "Daud dan jalur Natan menurut Lukas.",
    accent: "#6d28d9",
  },
  {
    id: "pembuangan",
    label: "Pembuangan & pemulihan",
    summary: "Sealtiel, Zerubabel, dan generasi sesudahnya.",
    accent: "#9a3412",
  },
  {
    id: "menunggu",
    label: "Masa menunggu",
    summary: "Generasi antar perjanjian menuju Eli.",
    accent: "#475569",
  },
  {
    id: "messias",
    label: "Sang Mesias",
    summary: "Yusuf (secara hukum) dan Yesus.",
    accent: "#b42318",
  },
];

/**
 * Urutan Adam → Yesus (Lukas 3, dibalik dari teks yang menulis Yesus → Adam).
 */
export const GENEALOGY_ADAM_TO_JESUS: GenealogyPerson[] = [
  {
    id: "adam",
    name: "Adam",
    generation: 1,
    era: "penciptaan",
    note: "Manusia pertama; garis keturunan dimulai dari dia.",
    characterSlug: "adam",
    reference: "Kejadian 5:1-5",
    passage: "Kejadian 5",
    verse: 1,
    featured: true,
  },
  {
    id: "set",
    name: "Set",
    alsoCalled: ["Seth"],
    generation: 2,
    era: "penciptaan",
    note: "Anak Adam yang melanjutkan garis pengharapan.",
    reference: "Kejadian 5:3-8",
    passage: "Kejadian 5",
    verse: 3,
  },
  {
    id: "enos",
    name: "Enos",
    generation: 3,
    era: "penciptaan",
    note: "Pada zamannya orang mulai memanggil nama TUHAN.",
    reference: "Kejadian 4:26",
    passage: "Kejadian 4",
    verse: 26,
  },
  {
    id: "kenan-1",
    name: "Kenan",
    generation: 4,
    era: "penciptaan",
    note: "Generasi keempat dari Adam.",
    reference: "Kejadian 5:9-14",
    passage: "Kejadian 5",
    verse: 9,
  },
  {
    id: "mahalaleel",
    name: "Mahalaleel",
    generation: 5,
    era: "penciptaan",
    note: "Leluhur dalam garis Set.",
    reference: "Kejadian 5:12-17",
    passage: "Kejadian 5",
    verse: 12,
  },
  {
    id: "yared",
    name: "Yared",
    generation: 6,
    era: "penciptaan",
    note: "Ayah Henokh.",
    reference: "Kejadian 5:15-20",
    passage: "Kejadian 5",
    verse: 15,
  },
  {
    id: "henokh",
    name: "Henokh",
    generation: 7,
    era: "penciptaan",
    note: "Bergaul dengan Allah dan diangkat — tidak mengalami maut seperti biasa.",
    reference: "Kejadian 5:21-24",
    passage: "Kejadian 5",
    verse: 24,
    featured: true,
  },
  {
    id: "metusalah",
    name: "Metusalah",
    generation: 8,
    era: "penciptaan",
    note: "Umur terpanjang yang dicatat dalam Kejadian.",
    reference: "Kejadian 5:25-27",
    passage: "Kejadian 5",
    verse: 27,
  },
  {
    id: "lamekh-nuh",
    name: "Lamekh",
    generation: 9,
    era: "penciptaan",
    note: "Ayah Nuh; mengharapkan penghiburan dari kerja keras tanah.",
    reference: "Kejadian 5:28-31",
    passage: "Kejadian 5",
    verse: 29,
  },
  {
    id: "nuh",
    name: "Nuh",
    generation: 10,
    era: "air-bah",
    note: "Diselamatkan dalam bahtera; perjanjian pelangi.",
    characterSlug: "nuh",
    reference: "Kejadian 6–9",
    passage: "Kejadian 6",
    verse: 9,
    featured: true,
  },
  {
    id: "sem",
    name: "Sem",
    generation: 11,
    era: "air-bah",
    note: "Anak Nuh; dari garisnyalah bangsa Semit dan Israel.",
    reference: "Kejadian 10:21-31",
    passage: "Kejadian 10",
    verse: 21,
    featured: true,
  },
  {
    id: "arpakhsad",
    name: "Arpakhsad",
    generation: 12,
    era: "air-bah",
    note: "Keturunan Sem menuju garis Eber.",
    reference: "Kejadian 11:10-13",
    passage: "Kejadian 11",
    verse: 10,
  },
  {
    id: "kenan-2",
    name: "Kenan",
    alsoCalled: ["Kainan"],
    generation: 13,
    era: "air-bah",
    note: "Disebut dalam Lukas (tradisi LXX); tidak selalu muncul di daftar Ibrani Kejadian 11.",
    reference: "Lukas 3:36",
    passage: "Lukas 3",
    verse: 36,
  },
  {
    id: "sala",
    name: "Sala",
    alsoCalled: ["Selah"],
    generation: 14,
    era: "air-bah",
    note: "Leluhur Eber.",
    reference: "Kejadian 11:12-15",
    passage: "Kejadian 11",
    verse: 12,
  },
  {
    id: "eber",
    name: "Eber",
    generation: 15,
    era: "air-bah",
    note: "Nama yang terkait dengan sebutan 'Ibrani'.",
    reference: "Kejadian 11:14-17",
    passage: "Kejadian 11",
    verse: 14,
    featured: true,
  },
  {
    id: "peleg",
    name: "Peleg",
    generation: 16,
    era: "air-bah",
    note: "Pada zamannya bumi terbagi.",
    reference: "Kejadian 10:25",
    passage: "Kejadian 10",
    verse: 25,
  },
  {
    id: "rehu",
    name: "Rehu",
    generation: 17,
    era: "air-bah",
    note: "Generasi menuju Serug.",
    reference: "Kejadian 11:18-21",
    passage: "Kejadian 11",
    verse: 18,
  },
  {
    id: "serug",
    name: "Serug",
    generation: 18,
    era: "air-bah",
    note: "Kakek buyut Abraham.",
    reference: "Kejadian 11:20-23",
    passage: "Kejadian 11",
    verse: 20,
  },
  {
    id: "nahor",
    name: "Nahor",
    generation: 19,
    era: "air-bah",
    note: "Ayah Terah.",
    reference: "Kejadian 11:22-25",
    passage: "Kejadian 11",
    verse: 22,
  },
  {
    id: "terah",
    name: "Terah",
    generation: 20,
    era: "air-bah",
    note: "Ayah Abraham; berangkat dari Ur menuju Haran.",
    reference: "Kejadian 11:24-32",
    passage: "Kejadian 11",
    verse: 31,
    featured: true,
  },
  {
    id: "abraham",
    name: "Abraham",
    alsoCalled: ["Abram"],
    generation: 21,
    era: "patriarkh",
    note: "Bapa iman; janji berkat bagi segala bangsa.",
    characterSlug: "abraham",
    reference: "Kejadian 12:1-3",
    passage: "Kejadian 12",
    verse: 1,
    featured: true,
  },
  {
    id: "ishak",
    name: "Ishak",
    generation: 22,
    era: "patriarkh",
    note: "Anak perjanjian dari Abraham dan Sara.",
    characterSlug: "ishak",
    reference: "Kejadian 21:1-3",
    passage: "Kejadian 21",
    verse: 1,
    featured: true,
  },
  {
    id: "yakub",
    name: "Yakub",
    alsoCalled: ["Israel"],
    generation: 23,
    era: "patriarkh",
    note: "Bapa dua belas suku Israel.",
    characterSlug: "yakub",
    reference: "Kejadian 32:28",
    passage: "Kejadian 32",
    verse: 28,
    featured: true,
  },
  {
    id: "yehuda",
    name: "Yehuda",
    generation: 24,
    era: "patriarkh",
    note: "Suku kerajaan; dari padanya muncul tongkat kerajaan.",
    characterSlug: "yehuda",
    reference: "Kejadian 49:8-10",
    passage: "Kejadian 49",
    verse: 10,
    featured: true,
  },
  {
    id: "peres",
    name: "Peres",
    generation: 25,
    era: "menuju-daud",
    note: "Anak Yehuda; garis menuju Daud.",
    reference: "Kejadian 38:29",
    passage: "Kejadian 38",
    verse: 29,
  },
  {
    id: "hezron",
    name: "Hezron",
    generation: 26,
    era: "menuju-daud",
    note: "Keturunan Peres.",
    reference: "Rut 4:18",
    passage: "Rut 4",
    verse: 18,
  },
  {
    id: "arni",
    name: "Arni",
    generation: 27,
    era: "menuju-daud",
    note: "Disebut dalam silsilah Lukas.",
    reference: "Lukas 3:33",
    passage: "Lukas 3",
    verse: 33,
  },
  {
    id: "admin",
    name: "Admin",
    generation: 28,
    era: "menuju-daud",
    note: "Disebut dalam silsilah Lukas.",
    reference: "Lukas 3:33",
    passage: "Lukas 3",
    verse: 33,
  },
  {
    id: "aminadab",
    name: "Aminadab",
    generation: 29,
    era: "menuju-daud",
    note: "Ayah Nahason; muncul juga di silsilah Rut.",
    reference: "Rut 4:19-20",
    passage: "Rut 4",
    verse: 19,
  },
  {
    id: "nahason",
    name: "Nahason",
    generation: 30,
    era: "menuju-daud",
    note: "Pemimpin Yehuda pada zaman keluaran.",
    reference: "Bilangan 1:7",
    passage: "Bilangan 1",
    verse: 7,
  },
  {
    id: "salmon",
    name: "Salmon",
    generation: 31,
    era: "menuju-daud",
    note: "Dalam Matius disebut suami Rahab.",
    reference: "Rut 4:20-21",
    passage: "Rut 4",
    verse: 20,
  },
  {
    id: "boas",
    name: "Boas",
    generation: 32,
    era: "menuju-daud",
    note: "Menebus Rut; kakek buyut Daud.",
    characterSlug: "boas",
    reference: "Rut 4:13-22",
    passage: "Rut 4",
    verse: 13,
    featured: true,
  },
  {
    id: "obed",
    name: "Obed",
    generation: 33,
    era: "menuju-daud",
    note: "Anak Boas dan Rut; ayah Isai.",
    reference: "Rut 4:17",
    passage: "Rut 4",
    verse: 17,
  },
  {
    id: "isai",
    name: "Isai",
    generation: 34,
    era: "menuju-daud",
    note: "Ayah Daud dari Betlehem.",
    reference: "1 Samuel 16:1",
    passage: "1 Samuel 16",
    verse: 1,
    featured: true,
  },
  {
    id: "daud",
    name: "Daud",
    generation: 35,
    era: "kerajaan",
    note: "Raja perjanjian. Lukas meneruskan lewat Natan; Matius lewat Salomo.",
    characterSlug: "daud",
    reference: "2 Samuel 7:12-16",
    passage: "2 Samuel 7",
    verse: 12,
    featured: true,
  },
  {
    id: "natan",
    name: "Natan",
    generation: 36,
    era: "kerajaan",
    note: "Anak Daud; jalur yang diikuti Lukas menuju Yesus.",
    reference: "Lukas 3:31",
    passage: "Lukas 3",
    verse: 31,
    featured: true,
  },
  {
    id: "matata",
    name: "Matata",
    generation: 37,
    era: "kerajaan",
    note: "Keturunan Natan.",
    reference: "Lukas 3:31",
    passage: "Lukas 3",
    verse: 31,
  },
  {
    id: "menna",
    name: "Menna",
    generation: 38,
    era: "kerajaan",
    note: "Generasi dalam garis Natan.",
    reference: "Lukas 3:31",
    passage: "Lukas 3",
    verse: 31,
  },
  {
    id: "melea",
    name: "Melea",
    generation: 39,
    era: "kerajaan",
    note: "Generasi dalam garis Natan.",
    reference: "Lukas 3:31",
    passage: "Lukas 3",
    verse: 31,
  },
  {
    id: "elyakim-1",
    name: "Elyakim",
    generation: 40,
    era: "kerajaan",
    note: "Generasi dalam garis Natan.",
    reference: "Lukas 3:30",
    passage: "Lukas 3",
    verse: 30,
  },
  {
    id: "yonam",
    name: "Yonam",
    generation: 41,
    era: "kerajaan",
    note: "Generasi dalam garis Natan.",
    reference: "Lukas 3:30",
    passage: "Lukas 3",
    verse: 30,
  },
  {
    id: "yusuf-yonam",
    name: "Yusuf",
    generation: 42,
    era: "kerajaan",
    note: "Salah satu Yusuf dalam silsilah Lukas (bukan suami Maria).",
    reference: "Lukas 3:30",
    passage: "Lukas 3",
    verse: 30,
  },
  {
    id: "yehuda-2",
    name: "Yehuda",
    generation: 43,
    era: "kerajaan",
    note: "Nama Yehuda muncul lagi dalam garis ini.",
    reference: "Lukas 3:30",
    passage: "Lukas 3",
    verse: 30,
  },
  {
    id: "simeon",
    name: "Simeon",
    generation: 44,
    era: "kerajaan",
    note: "Generasi menuju Lewi.",
    reference: "Lukas 3:30",
    passage: "Lukas 3",
    verse: 30,
  },
  {
    id: "lewi-1",
    name: "Lewi",
    generation: 45,
    era: "kerajaan",
    note: "Generasi dalam silsilah Lukas.",
    reference: "Lukas 3:29",
    passage: "Lukas 3",
    verse: 29,
  },
  {
    id: "matat-1",
    name: "Matat",
    generation: 46,
    era: "kerajaan",
    note: "Generasi dalam silsilah Lukas.",
    reference: "Lukas 3:29",
    passage: "Lukas 3",
    verse: 29,
  },
  {
    id: "yorim",
    name: "Yorim",
    generation: 47,
    era: "kerajaan",
    note: "Generasi dalam silsilah Lukas.",
    reference: "Lukas 3:29",
    passage: "Lukas 3",
    verse: 29,
  },
  {
    id: "eliezer",
    name: "Eliezer",
    generation: 48,
    era: "kerajaan",
    note: "Generasi dalam silsilah Lukas.",
    reference: "Lukas 3:29",
    passage: "Lukas 3",
    verse: 29,
  },
  {
    id: "yesua",
    name: "Yesua",
    generation: 49,
    era: "kerajaan",
    note: "Generasi dalam silsilah Lukas.",
    reference: "Lukas 3:29",
    passage: "Lukas 3",
    verse: 29,
  },
  {
    id: "er",
    name: "Er",
    generation: 50,
    era: "kerajaan",
    note: "Generasi dalam silsilah Lukas.",
    reference: "Lukas 3:28",
    passage: "Lukas 3",
    verse: 28,
  },
  {
    id: "elmadam",
    name: "Elmadam",
    generation: 51,
    era: "kerajaan",
    note: "Generasi dalam silsilah Lukas.",
    reference: "Lukas 3:28",
    passage: "Lukas 3",
    verse: 28,
  },
  {
    id: "kosam",
    name: "Kosam",
    generation: 52,
    era: "kerajaan",
    note: "Generasi dalam silsilah Lukas.",
    reference: "Lukas 3:28",
    passage: "Lukas 3",
    verse: 28,
  },
  {
    id: "adi",
    name: "Adi",
    generation: 53,
    era: "kerajaan",
    note: "Generasi dalam silsilah Lukas.",
    reference: "Lukas 3:28",
    passage: "Lukas 3",
    verse: 28,
  },
  {
    id: "melki-1",
    name: "Melki",
    generation: 54,
    era: "kerajaan",
    note: "Generasi menuju Neri.",
    reference: "Lukas 3:28",
    passage: "Lukas 3",
    verse: 28,
  },
  {
    id: "neri",
    name: "Neri",
    generation: 55,
    era: "pembuangan",
    note: "Ayah Sealtiel dalam catatan Lukas.",
    reference: "Lukas 3:27",
    passage: "Lukas 3",
    verse: 27,
  },
  {
    id: "sealtiel",
    name: "Sealtiel",
    alsoCalled: ["Sealtiel"],
    generation: 56,
    era: "pembuangan",
    note: "Tokoh zaman pembuangan; ayah Zerubabel dalam silsilah.",
    reference: "Lukas 3:27",
    passage: "Lukas 3",
    verse: 27,
    featured: true,
  },
  {
    id: "zerubabel",
    name: "Zerubabel",
    generation: 57,
    era: "pembuangan",
    note: "Pemimpin pemulihan; membangun kembali mezbah dan Bait Suci.",
    reference: "Ezra 3:2",
    passage: "Ezra 3",
    verse: 2,
    featured: true,
  },
  {
    id: "resa",
    name: "Resa",
    generation: 58,
    era: "pembuangan",
    note: "Keturunan Zerubabel menurut Lukas.",
    reference: "Lukas 3:27",
    passage: "Lukas 3",
    verse: 27,
  },
  {
    id: "yohanan",
    name: "Yohanan",
    generation: 59,
    era: "menunggu",
    note: "Generasi masa antar perjanjian.",
    reference: "Lukas 3:27",
    passage: "Lukas 3",
    verse: 27,
  },
  {
    id: "yoda",
    name: "Yoda",
    generation: 60,
    era: "menunggu",
    note: "Generasi masa antar perjanjian.",
    reference: "Lukas 3:26",
    passage: "Lukas 3",
    verse: 26,
  },
  {
    id: "yosekh",
    name: "Yosekh",
    generation: 61,
    era: "menunggu",
    note: "Generasi masa antar perjanjian.",
    reference: "Lukas 3:26",
    passage: "Lukas 3",
    verse: 26,
  },
  {
    id: "simei",
    name: "Simei",
    generation: 62,
    era: "menunggu",
    note: "Generasi masa antar perjanjian.",
    reference: "Lukas 3:26",
    passage: "Lukas 3",
    verse: 26,
  },
  {
    id: "matatia-1",
    name: "Matatia",
    generation: 63,
    era: "menunggu",
    note: "Generasi masa antar perjanjian.",
    reference: "Lukas 3:26",
    passage: "Lukas 3",
    verse: 26,
  },
  {
    id: "maat",
    name: "Maat",
    generation: 64,
    era: "menunggu",
    note: "Generasi masa antar perjanjian.",
    reference: "Lukas 3:26",
    passage: "Lukas 3",
    verse: 26,
  },
  {
    id: "nagai",
    name: "Nagai",
    generation: 65,
    era: "menunggu",
    note: "Generasi masa antar perjanjian.",
    reference: "Lukas 3:25",
    passage: "Lukas 3",
    verse: 25,
  },
  {
    id: "hesli",
    name: "Hesli",
    generation: 66,
    era: "menunggu",
    note: "Generasi masa antar perjanjian.",
    reference: "Lukas 3:25",
    passage: "Lukas 3",
    verse: 25,
  },
  {
    id: "nahum",
    name: "Nahum",
    generation: 67,
    era: "menunggu",
    note: "Generasi masa antar perjanjian.",
    reference: "Lukas 3:25",
    passage: "Lukas 3",
    verse: 25,
  },
  {
    id: "amos",
    name: "Amos",
    generation: 68,
    era: "menunggu",
    note: "Generasi masa antar perjanjian.",
    reference: "Lukas 3:25",
    passage: "Lukas 3",
    verse: 25,
  },
  {
    id: "matatia-2",
    name: "Matatia",
    generation: 69,
    era: "menunggu",
    note: "Generasi masa antar perjanjian.",
    reference: "Lukas 3:25",
    passage: "Lukas 3",
    verse: 25,
  },
  {
    id: "yusuf-yanai",
    name: "Yusuf",
    generation: 70,
    era: "menunggu",
    note: "Salah satu Yusuf dalam silsilah (bukan suami Maria).",
    reference: "Lukas 3:24",
    passage: "Lukas 3",
    verse: 24,
  },
  {
    id: "yanai",
    name: "Yanai",
    generation: 71,
    era: "menunggu",
    note: "Generasi menuju Melki.",
    reference: "Lukas 3:24",
    passage: "Lukas 3",
    verse: 24,
  },
  {
    id: "melki-2",
    name: "Melki",
    generation: 72,
    era: "menunggu",
    note: "Generasi menuju Lewi.",
    reference: "Lukas 3:24",
    passage: "Lukas 3",
    verse: 24,
  },
  {
    id: "lewi-2",
    name: "Lewi",
    generation: 73,
    era: "menunggu",
    note: "Generasi menuju Matat.",
    reference: "Lukas 3:24",
    passage: "Lukas 3",
    verse: 24,
  },
  {
    id: "matat-2",
    name: "Matat",
    generation: 74,
    era: "menunggu",
    note: "Ayah Eli menurut Lukas.",
    reference: "Lukas 3:24",
    passage: "Lukas 3",
    verse: 24,
  },
  {
    id: "eli",
    name: "Eli",
    alsoCalled: ["Heli"],
    generation: 75,
    era: "menunggu",
    note: "Disebut ayah Yusuf dalam Lukas — sering dipahami sebagai garis Maria secara hukum.",
    reference: "Lukas 3:23",
    passage: "Lukas 3",
    verse: 23,
    featured: true,
  },
  {
    id: "yusuf",
    name: "Yusuf",
    alsoCalled: ["suami Maria"],
    generation: 76,
    era: "messias",
    note: "Secara hukum ayah Yesus; Lukas menyebutnya anak Eli.",
    characterSlug: "yusuf-suami-maria",
    reference: "Lukas 3:23",
    passage: "Lukas 3",
    verse: 23,
    featured: true,
  },
  {
    id: "yesus",
    name: "Yesus",
    alsoCalled: ["Kristus", "Mesias"],
    generation: 77,
    era: "messias",
    note: "Penggenapan janji — Anak Allah yang masuk dalam sejarah manusia.",
    reference: "Lukas 3:23-38",
    passage: "Lukas 3",
    verse: 23,
    featured: true,
  },
];

/** Cabang Matius dari Daud (untuk perbandingan di UI). */
export const MATTHEW_BRANCH_FROM_DAVID = [
  { name: "Salomo", note: "Anak Daud; jalur raja Yehuda", characterSlug: "salomo" },
  { name: "Rehabeam", note: "Raja Yehuda" },
  { name: "Abia", note: "Raja Yehuda" },
  { name: "Asa", note: "Raja Yehuda" },
  { name: "Yosafat", note: "Raja Yehuda" },
  { name: "Yoram", note: "Raja Yehuda" },
  { name: "Uzia", note: "Raja Yehuda" },
  { name: "Yotam", note: "Raja Yehuda" },
  { name: "Ahas", note: "Raja Yehuda" },
  { name: "Hizkia", note: "Raja Yehuda", characterSlug: "hizkia" },
  { name: "Manasye", note: "Raja Yehuda" },
  { name: "Amon", note: "Raja Yehuda" },
  { name: "Yosia", note: "Raja Yehuda" },
  { name: "Yekhonya", note: "Pembuangan ke Babel" },
  { name: "Sealtiel", note: "Zaman pembuangan" },
  { name: "Zerubabel", note: "Pemulihan" },
  { name: "… hingga Yakub ayah Yusuf", note: "Matius 1:12-16" },
  { name: "Yusuf suami Maria", note: "Ayah hukum Yesus", characterSlug: "yusuf-suami-maria" },
  { name: "Yesus", note: "Disebut Kristus" },
] as const;

export function getGenealogyEra(id: GenealogyEraId) {
  return GENEALOGY_ERAS.find((era) => era.id === id) ?? GENEALOGY_ERAS[0]!;
}

export function getGenealogyPerson(id: string) {
  return GENEALOGY_ADAM_TO_JESUS.find((person) => person.id === id) ?? null;
}

export function getGenealogyCount() {
  return GENEALOGY_ADAM_TO_JESUS.length;
}

export function getFeaturedGenealogy() {
  return GENEALOGY_ADAM_TO_JESUS.filter((person) => person.featured);
}

export function searchGenealogy(query: string) {
  const q = query.trim().toLowerCase();
  if (!q) return [...GENEALOGY_ADAM_TO_JESUS];
  return GENEALOGY_ADAM_TO_JESUS.filter((person) => {
    const haystack = [
      person.name,
      person.note,
      person.id,
      ...(person.alsoCalled ?? []),
      getGenealogyEra(person.era).label,
      person.reference ?? "",
    ]
      .join(" ")
      .toLowerCase();
    return haystack.includes(q);
  });
}

export function genealogyPassageHref(person: GenealogyPerson) {
  if (!person.passage) return null;
  const params = new URLSearchParams();
  params.set("browse", "1");
  params.set("passage", person.passage);
  if (person.verse) params.set("verse", String(person.verse));
  return `/baca?${params.toString()}`;
}
