/** Teks UI — profesional, to the point, tetap hangat. */
export const copy = {
  app: {
    name: "Baca Alkitab Bersama",
    metaDescription:
      "Platform baca Alkitab untuk komunitas: jadwal harian, kelompok, dan ruang renungan yang aman.",
  },

  nav: {
    home: "Beranda",
    read: "Baca Alkitab",
    explore: "Explore Alkitab",
    schedule: "Jadwal Baca",
    notes: "Renungan",
    myReflections: "Refleksiku",
    journal: "Jurnalku",
    chat: "Chat",
    group: "Kelompokku",
    myGroup: "Kelompokku",
    features: "Fitur",
    notifications: "Notifikasi",
    profile: "Profil",
  },

  globalSearch: {
    title: "Cari di mana saja",
    placeholder: "Cari kitab, tokoh, topik, halaman…",
    emptyQueryHint: "Pilih rekomendasi populer di bawah atau mulai ketik.",
    noResults: "Tidak ada hasil. Coba kata lain atau nama kitab/pasal.",
    shortcutHint: "⌘K",
    groupPages: "Halaman",
    groupBible: "Alkitab",
    groupBooks: "Sejarah kitab",
    groupCharacters: "Tokoh",
    groupStories: "Kisah",
    groupTopics: "Topik",
    groupGlossary: "Glosarium",
    groupPlaces: "Tempat",
    groupCustoms: "Kebiasaan",
    groupPopular: "Pencarian populer",
    groupRecent: "Pencarian terakhir",
    clearRecent: "Hapus riwayat",
  },

  explore: {
    eyebrow: "Portal pendalaman",
    title: "Explore",
    subtitle:
      "Pintu masuk belajar Alkitab lebih dalam — dari kitab dan topik, tokoh dan kisah, hingga peta dan istilah.",
    statsSummary: (
      books: number,
      topics: number,
      characters: number,
      stories: number,
      terms: number,
    ) =>
      `${books} kitab · ${topics} topik · ${characters} tokoh · ${stories} kisah · ${terms} istilah`,
    featuredTitle: "Mulai dari sini",
    featuredHint: "Pintu masuk paling sering dipakai untuk memulai pendalaman.",
    popularTitle: "Sering dicari",
    sectionWord: "Firman & teks",
    sectionWordHint: "Kitab, topik Firman, dan kamus istilah Alkitab.",
    sectionStories: "Kisah & tokoh",
    sectionStoriesHint:
      "Kisah penting Alkitab, profil tokoh, dan pelajaran dari hidup mereka.",
    sectionContext: "Konteks & latar",
    sectionContextHint: "Kebiasaan zaman Alkitab, peta tempat, dan silsilah.",
    backToExplore: "Explore",
    viewFullImage: "Lihat penuh",
    viewFullImageHint: "Ketuk untuk lihat versi penuh",
    closeFullImage: "Tutup",
    imageSourceLabel: "Sumber",
    openDestination: "Jelajahi",
    sneakPeekEyebrow: "Sneak peek hari ini",
    sneakPeekCta: "Baca profil lengkap",
    whyItMattersLabel: "Mengapa penting",
    keyVerseLabel: "Ayat kunci",
    lifeLessonLabel: "Pelajaran hidup",
    keyMomentsLabel: "Momen kunci",
    relatedStoryLabel: "Kisah terkait",
    readStoryCta: "Baca kisah",
    readPassageCta: "Baca ayat",
    shortReflectionLabel: "Renungan singkat",
    topCharactersTitle: "Tokoh paling sering dicari",
    topCharactersHint:
      "Profil populer dengan ringkasan singkat — ketuk untuk pelajaran lengkap.",
    didYouKnowTitle: "Tahukah kamu?",
    didYouKnowContextLabel: "Konteks lebih dalam",
    didYouKnowRelatedLabel: "Fakta terkait",
    didYouKnowCta: "Pelajari lebih lanjut",
    didYouKnowReadStory: "Baca kisah lengkap",
    portalHeroEyebrow: "Sorotan hari ini",
    highlightsTitle: "Artikel pilihan",
    browseIndexTitle: "Indeks ensiklopedia",
    readArticleCta: "Baca selengkapnya",
    aiDisclaimer:
      "Semua informasi di Explore ini disediakan oleh AI. Mohon verifikasi kembali kebenarannya dengan Alkitab dan sumber tepercaya.",
    popularLinks: [
      { label: "Keluaran", href: "/baca/kisah/keluaran-mesir" },
      { label: "Kasih", href: "/baca/topik/kasih" },
      { label: "Daud", href: "/baca/tokoh/daud" },
      { label: "Anugerah", href: "/baca/glosarium/anugerah" },
      { label: "Betlehem", href: "/baca/peta/betlehem" },
      { label: "Doa", href: "/baca/topik/doa" },
      { label: "Musa", href: "/baca/tokoh/musa" },
    ] as const,
  },

  chat: {
    title: "Chat kelompok",
    subtitle: "Ruang percakapan kelompok — saling menguatkan.",
    lockedTitle: "Belum ada refleksi hari ini",
    lockedHint:
      "Tulis refleksi bacaan di bawah — otomatis masuk ke chat kelompok.",
    writeToUnlock: "Tulis refleksi",
    placeholder: "Tulis pesan… ketik @ untuk mention (@all untuk semua)",
    reflectionPlaceholder:
      "Tulis refleksi dari bacaanmu… langsung terkirim ke chat kelompok",
    composerModeAria: "Jenis pesan",
    composerModeReflection: "Refleksi",
    composerModeChat: "Chat",
    reflectionSentToast: "Refleksi terkirim ke chat kelompok",
    send: "Kirim",
    empty: "Belum ada pesan. Mulai percakapan dengan kelompokmu.",
    mentionLabel: "Mention anggota",
    mentionEmpty: "Tidak ada anggota yang cocok",
    mentionAll: "Semua anggota",
    mentionAllHandle: "@all",
    delete: "Hapus",
    deleteTitle: "Hapus pesan?",
    deleteDescription:
      "Isi pesan diganti tanda “pesan dihapus” di chat kelompok. Hanya bisa dalam 15 menit setelah dikirim.",
    deleteConfirm: "Hapus pesan",
    deleteCancel: "Batal",
    deleteSuccess: "Pesan dihapus",
    deleteExpired: "Pesan hanya bisa dihapus dalam 15 menit setelah dikirim.",
    deleteWindowHint: "Bisa dihapus",
    deletedPlaceholder: "Pesan ini dihapus",
    deletedReflectionPlaceholder: "Refleksi ini dihapus",
    reflectionBadge: "Refleksi bacaan",
    reflectionShared: "Membagikan refleksi",
    messageBadge: "Chat",
    legendReflection: "Refleksi",
    legendChat: "Chat biasa",
    filterAria: "Filter isi chat",
    filterAll: "Semua",
    filterReflection: "Refleksi",
    filterChat: "Chat biasa",
    filterEmptyReflection: "Belum ada refleksi bacaan di chat ini.",
    filterEmptyChat: "Belum ada chat biasa.",
    emojiAria: "Pilih emoji",
    gifAria: "Cari & kirim GIF",
    gifSearchPlaceholder: "Cari GIF… atau tempel tautan https",
    gifEmpty: "Tidak ada GIF. Coba kata lain atau tempel tautan.",
    gifLoading: "Memuat GIF…",
    gifSourceHint: "Sumber: Giphy / Tenor / tautan",
    gifRemove: "Hapus GIF",
    gifPreview: "Pratinjau GIF",
  },

  read: {
    title: "Baca",
    hint: "Mulai dari bacaan hari ini. Jadwal lengkap ada di bawah.",
    tabBible: "Hari ini",
    tabSchedule: "Jadwal",
  },

  topics: {
    eyebrow: "Jelajahi Alkitab",
    title: "Topik Firman",
    subtitle:
      "Puluhan tema Firman — kasih, ketakutan, doa, kerja, keselamatan, dan lainnya. Baca ayat kunci, lalu lanjut ke konteks pasal.",
    subtitleShort: "Tema Firman dengan ayat kunci dan renungan.",
    searchPlaceholder: "Cari topik, misalnya kasih atau ketakutan…",
    categoryAria: "Kategori topik",
    featured: "Populer untuk memulai",
    allTopics: "Semua topik",
    results: "Hasil pencarian",
    emptySearch: "Tidak ada topik yang cocok. Coba kata lain.",
    catalogCount: (count: number) => `${count} topik siap dijelajahi`,
    keyVerses: "Ayat kunci",
    explanationTitle: "Penjelasan",
    reflectionTitle: "Renungan",
    prayerTitle: "Doa",
    relatedTitle: "Topik terkait",
    readInContext: "Baca di konteks",
    contextHint:
      "Ayat kunci adalah pintu masuk. Baca pasal lengkapnya supaya konteksnya utuh.",
    backToRead: "Kembali ke Baca",
    backToTopics: "Semua topik",
    openCta: "Jelajahi topik",
  },

  customs: {
    eyebrow: "Adat & ritual",
    title: "Kebiasaan Alkitab",
    subtitle:
      "Sunat, Paskah, aturan kesucian, lepas sandal di tempat kudus, dan adat istiadat lain yang tercatat dalam Firman — latar, praktik, makna, dan ayat kunci.",
    subtitleShort: "Adat, ritual, dan kebiasaan yang tercatat dalam Alkitab.",
    searchPlaceholder: "Cari kebiasaan, misalnya paskah atau sunat…",
    categoryLabel: "Kategori",
    featured: "Sering dicari",
    allCustoms: "Semua kebiasaan",
    results: "Hasil pencarian",
    emptySearch: "Tidak ada kebiasaan yang cocok. Coba kata lain.",
    catalogCount: (count: number) => `${count} kebiasaan siap dijelajahi`,
    backgroundTitle: "Latar & konteks",
    practiceTitle: "Apa yang dilakukan",
    meaningTitle: "Makna rohani",
    todayTitle: "Bagi kita hari ini",
    keyVerses: "Ayat kunci",
    relatedTitle: "Kebiasaan terkait",
    readInContext: "Baca di konteks",
    contextHint:
      "Adat istiadat Alkitab hidup dalam konteks perjanjian dan budaya. Baca ayat lengkapnya untuk memahami situasinya.",
    backToCustoms: "Semua kebiasaan",
  },

  stories: {
    eyebrow: "Narasi Alkitab",
    title: "Kisah Penting",
    subtitle:
      "Kisah-kisah besar Alkitab — dari penciptaan hingga gereja mula-mula. Ringkasan, pelajaran, dan pintu masuk baca pasal lengkap.",
    subtitleShort: "Kisah penting Alkitab dengan pasal kunci.",
    searchPlaceholder: "Cari kisah, misalnya keluaran atau pentakosta…",
    categoryAria: "Kategori kisah",
    featured: "Kisah populer",
    allStories: "Semua kisah",
    results: "Hasil pencarian",
    emptySearch: "Tidak ada kisah yang cocok. Coba kata lain.",
    catalogCount: (count: number) => `${count} kisah siap dijelajahi`,
    comicIllustration: "Ilustrasi komik",
    backgroundTitle: "Latar & konteks",
    narrativeTitle: "Kisah lengkap",
    momentsTitle: "Momen kunci",
    lessonsTitle: "Pelajaran",
    reflectionTitle: "Renungan",
    prayerTitle: "Doa singkat",
    keyPassages: "Ayat & pasal kunci",
    relatedCharacters: "Tokoh terkait",
    relatedPlaces: "Tempat terkait",
    readInContext: "Baca di konteks",
    hint: "Ringkasan ini membantu mengenal kisahnya. Baca pasal lengkap supaya konteksnya utuh dalam Alkitab.",
    backToStories: "Semua kisah",
    openCta: "Kisah Penting",
  },

  glossary: {
    eyebrow: "Kamus singkat",
    title: "Glosarium",
    subtitle:
      "Lebih dari seratus istilah Alkitab — dari anugerah dan Paskah hingga Shalom, Hesed, dan Logos — dijelaskan dengan bahasa sehari-hari.",
    subtitleShort: "Istilah Alkitab, Ibrani, dan Yunani dalam bahasa sehari-hari.",
    searchPlaceholder: "Cari istilah, misalnya hesed, shalom, atau anugerah…",
    categoryAria: "Kategori istilah",
    featured: "Sering ditanyakan",
    allTerms: "Semua istilah",
    results: "Hasil pencarian",
    emptySearch: "Tidak ada istilah yang cocok. Coba kata lain.",
    catalogCount: (count: number) => `${count} istilah siap dicari`,
    explanation: "Penjelasan",
    keyVerse: "Ayat pintu masuk",
    readInContext: "Baca di konteks",
    hint: "Ini pengantar singkat, bukan kamus teologi lengkap. Baca ayat di konteks pasalnya supaya maknanya utuh.",
    backToRead: "Kembali ke Baca",
    backToList: "Semua istilah",
    openCta: "Glosarium",
  },

  characters: {
    eyebrow: "Kenali tokohnya",
    title: "Tokoh Alkitab",
    subtitle:
      "Latar hidup, kisah mendalam, momen kunci, pelajaran, renungan, doa, dan ayat — kenali tokoh Alkitab lebih utuh.",
    subtitleShort: "Profil, kisah, dan pelajaran tokoh Alkitab.",
    searchPlaceholder: "Cari tokoh, misalnya Daud, Rahab, atau Ayub…",
    categoryAria: "Kategori tokoh",
    categoryLabel: "Kategori",
    featured: "Sering dicari",
    allCharacters: "Semua tokoh",
    results: "Hasil pencarian",
    emptySearch: "Tidak ada tokoh yang cocok. Coba nama lain atau ubah filter.",
    catalogCount: (count: number) => `${count} tokoh siap dikenal`,
    filtersTitle: "Pencarian lanjutan",
    filtersHint:
      "Pilih satu atau lebih opsi per kategori — bisa digabung dengan pencarian nama.",
    filterGender: "Jenis kelamin",
    filterAge: "Usia meninggal",
    filterBirthPlace: "Tempat lahir",
    filterOccupation: "Pekerjaan",
    filterField: "Bidang gerak",
    filterStoryContext: "Konteks cerita",
    filterAll: "Semua",
    filterSelected: (count: number) =>
      count === 1 ? "1 dipilih" : `${count} dipilih`,
    filterReset: "Reset filter",
    filterActive: (count: number) =>
      count === 1 ? "1 filter aktif" : `${count} filter aktif`,
    backgroundTitle: "Latar & konteks",
    storyTitle: "Kisah hidup",
    momentsTitle: "Momen kunci",
    lessonsTitle: "Pelajaran untuk kita",
    reflectionTitle: "Renungan",
    prayerTitle: "Doa singkat",
    keyVerse: "Ayat pintu masuk",
    keyVerses: "Ayat-ayat kunci",
    relatedTitle: "Tokoh terkait",
    familyTitle: "Keluarga & hubungan",
    familyFather: "Ayah",
    familyMother: "Ibu",
    familySpouse: "Pasangan",
    familyInLaws: "Mertua & ipar",
    familySiblings: "Saudara",
    familyChildren: "Anak",
    familyNotRecorded: "Tidak dicatat dalam Alkitab",
    readInContext: "Baca di konteks",
    hint: "Profil ini membantu mengenal tokohnya. Baca pasal terkait supaya kisahnya utuh dalam konteks Alkitab.",
    backToRead: "Kembali ke Baca",
    twelveDisciplesTitle: "12 murid Yesus",
    twelveDisciplesSubtitle:
      "Daftar resmi murid yang dipanggil Yesus (Matius 10:2–4). Ketuk nama untuk profil lengkap — kisah, ayat, dan pelajaran.",
    twelveDisciplesIntro:
      "Yesus memanggil dua belas laki-laki untuk dekat dengan-Nya, belajar kerajaan Allah, dan diutus memberitakan. Mereka bukan sempurna — ada yang ragu, menyangkal, bahkan mengkhianati — tetapi kisah mereka mengajar iman, panggilan, dan pemulihan.",
    twelveDisciplesReference: "Matius 10:2–4 · Markus 3:16–19",
    twelveDisciplesCount: (found: number, total: number) =>
      `${found} dari ${total} profil lengkap`,
    twelveDisciplesAlsoKnown: "Juga dikenal:",
    otherNotableTitle: "Tokoh penting lainnya",
    otherNotableSubtitle:
      "Perjanjian Baru penuh tokoh di luar kedua belas — rasul, saksi, dan pelayan jemaat yang melanjutkan kisah Injil.",
    readProfile: "Baca profil",
    backToList: "Semua tokoh",
    openCta: "Tokoh Alkitab",
  },

  places: {
    eyebrow: "Peta zaman dulu",
    title: "Peta Alkitab",
    subtitle:
      "Betlehem, Mesir, Yerusalem, Babel, dan lainnya — lihat di Google Maps, ketuk pin untuk kisah yang terjadi di sana.",
    subtitleShort: "Tempat penting dan kisah di peta.",
    searchPlaceholder: "Cari tempat atau kisah, misalnya Betlehem…",
    regionAria: "Wilayah peta",
    kindAria: "Jenis tempat",
    kindLabel: "Jenis",
    regionLabel: "Wilayah",
    allKinds: "Semua jenis",
    featured: "Tempat yang sering dibaca",
    allPlaces: "Semua tempat",
    results: "Hasil pencarian",
    emptySearch: "Tidak ada tempat yang cocok. Coba kata lain.",
    catalogCount: (places: number, stories: number) =>
      `${places} tempat · ${stories} kisah`,
    storiesTitle: "Kisah di tempat ini",
    readInContext: "Baca di konteks",
    backToRead: "Kembali ke Baca",
    backToList: "Semua tempat",
    backToMap: "Kembali ke peta",
    openCta: "Peta Alkitab",
    mapHint:
      "Pin menandai perkiraan lokasi modern dari tempat Alkitab. Pakai tombol Ukur jarak, lalu ketuk dua pin untuk melihat jaraknya (bukan batas politik zaman dulu).",
    hint: "Setiap kisah adalah pintu masuk. Baca pasal lengkapnya supaya konteksnya utuh.",
  },

  genealogy: {
    eyebrow: "Dari awal sampai penggenapan",
    title: "Silsilah Adam → Yesus",
    subtitle:
      "Peta garis keturunan menurut Lukas 3 — dari Adam sampai Yesus, dengan catatan jalur Matius dari Daud.",
    subtitleShort: "Garis keturunan Adam hingga Yesus.",
    searchPlaceholder: "Cari nama, misalnya Abraham atau Zerubabel…",
    catalogCount: (count: number) => `${count} generasi dalam garis Lukas`,
    filteredCount: (shown: number, total: number) =>
      `${shown} dari ${total} generasi`,
    passageRef: "Lukas 3:23–38",
    eraLabel: "Zaman",
    eraAria: "Saring menurut zaman silsilah",
    allEras: "Semua zaman",
    featuredOnly: "Hanya tokoh kunci",
    featuredJump: "Lompat cepat",
    featured: "Tokoh kunci",
    treeTitle: "Garis keturunan",
    detailTitle: "Detail generasi",
    progressFrom: "Adam",
    progressTo: "Yesus",
    progressLabel: (percent: number) => `${percent}% perjalanan`,
    generationShort: (n: number) => `gen. ${n}`,
    alsoCalled: "Juga",
    prev: "Sebelumnya",
    next: "Berikutnya",
    matthewBranch: "Cabang Matius (lewat Salomo)",
    hideMatthewBranch: "Sembunyikan cabang Matius",
    matthewNote:
      "Matius 1 menempuh jalur raja dari Daud melalui Salomo. Lukas 3 menempuh jalur melalui Natan. Keduanya bertemu lagi pada Yesus.",
    readInContext: "Baca di konteks",
    openCharacter: "Profil tokoh",
    emptySearch: "Tidak ada nama yang cocok. Coba kata lain.",
    hint: "Ini peta belajar berdasarkan Lukas 3:23–38. Beberapa ejaan dan urutan mengikuti tradisi teks yang dipakai terjemahan; bandingkan dengan Matius 1 untuk jalur lain dari Daud.",
    backToRead: "Kembali ke Baca",
    openCta: "Silsilah",
  },

  bookIntro: {
    eyebrow: "Kenali kitabnya",
    title: "Sejarah Kitab",
    subtitle:
      "Isi kitab, tokoh, latar, tema, kerangka, dan sumber rujukan — pengantar tiap kitab Alkitab.",
    subtitleShort: "Pengantar isi, tema, dan tokoh tiap kitab.",
    searchPlaceholder: "Cari kitab atau tokoh, misalnya Kejadian atau Paulus…",
    allBooks: "Semua",
    listTitle: "66 kitab",
    results: "Hasil pencarian",
    emptySearch: "Tidak ada kitab yang cocok. Coba nama lain.",
    overviewTitle: "Latar belakang",
    aboutTitle: "Kitab ini menceritakan tentang apa",
    themesTitle: "Tema utama",
    charactersTitle: "Tokoh yang terlibat",
    charactersHint: "Tokoh utama yang muncul atau berperan penting dalam kitab ini.",
    outlineTitle: "Kerangka besar",
    deeperTitle: "Pendalaman",
    notesTitle: "Catatan penafsiran",
    sourcesTitle: "Sumber rujukan",
    sourcesHint:
      "Teks ini sintesis ringkas untuk pembaca awam — bukan kutipan literal satu buku. Lihat daftar sumber di bawah.",
    chaptersLabel: "pasal",
    fields: {
      who: "Siapa yang menulis",
      when: "Kapan",
      how: "Bagaimana ditulis",
      why: "Mengapa ditulis",
      audience: "Untuk siapa",
    },
    readBook: "Baca kitab ini",
    backToRead: "Kembali ke Baca",
    backToList: "Semua kitab",
    openCta: "Sejarah kitab",
    aboutBook: "Tentang kitab",
    disclaimer:
      "Pengantar disusun dari tradisi gereja dan literatur pengantar Alkitab yang tercantum di sumber. Di beberapa kitab, atribusi/penanggalan akademis berbeda dari tradisi — itu dicatat di bagian catatan.",
  },

  worship: {
    title: "Lagu worship",
    toolbarHint: "Musik worship — ketuk buka, tahan untuk geser",
    hint: "Instrumental lembut biar lebih tenang baca Firman. Butuh koneksi YouTube. TTS berhenti otomatis saat musik diputar.",
    play: "Putar",
    stop: "Berhenti",
    close: "Tutup",
    minimize: "Perkecil",
    expand: "Perbesar",
    nowPlaying: "Sedang diputar",
    openYoutube: "Buka di YouTube",
    dragHint: "Tahan lalu geser",
    bubbleLabel: "Musik sedang diputar — ketuk untuk buka panel",
  },

  common: {
    comingSoon: "Segera hadir",
    comingSoonHint: "Fitur ini sedang disiapkan.",
    back: "Kembali",
    members: "anggota",
    days: "hari",
    you: "(kamu)",
    roles: {
      admin: "Admin",
      leader: "Ketua",
      member: "Anggota",
    },
  },

  landing: {
    heroLead: "Baca, renung, dan tumbuh",
    heroAccent: "bersama kelompokmu setiap hari.",
    subhero:
      "Baca Firman bersama komunitas — dengan jadwal yang jelas dan dukungan yang hangat.",
    features: {
      schedule: {
        title: "Jadwal Baca",
        description: "Pasal dan renungan sudah siap. Buka, lalu mulai.",
      },
      group: {
        title: "Kelompok",
        description: "Baca bersama kelompok. Saling mendukung tanpa tekanan absensi.",
      },
      notes: {
        title: "Renungan pribadi",
        description: "Tulis refleksi. Bagikan hanya jika kamu ingin.",
      },
    },
    journeyTitle: "Tiga langkah yang sederhana",
    journeySubtitle: "Dari bacaan harian, ke refleksi pribadi, lalu dukungan kelompok.",
    journey: {
      read: {
        title: "Baca",
        description: "Ikuti jadwal harian. Pasal siap menunggu.",
      },
      reflect: {
        title: "Renung",
        description: "Catat yang berbicara padamu — tanpa tekanan untuk membagikan.",
      },
      grow: {
        title: "Tumbuh bersama",
        description: "Saling menguatkan di kelompok. Perjalanan, bukan absensi.",
      },
    },
    forWhomTitle: "Untuk komunitas yang ingin konsisten",
    forWhomSubtitle:
      "Gereja, kantor, youth, atau small group — satu program, banyak kelompok.",
    faqTitle: "Pertanyaan yang sering diajukan",
    faqSubtitle: "Jawaban singkat agar kamu tahu apa yang bisa diharapkan.",
    faq: [
      {
        q: "Apa itu Baca Alkitab Bersama?",
        a: "Platform baca Alkitab untuk komunitas: jadwal harian, kelompok kecil, dan ruang renungan yang aman — tanpa suasana absensi.",
      },
      {
        q: "Siapa yang dapat menggunakannya?",
        a: "Admin mengelola program, ketua mendampingi kelompok, dan anggota fokus membaca serta merenung. Cocok untuk gereja, youth, kantor, atau small group.",
      },
      {
        q: "Apakah renungan wajib dibagikan?",
        a: "Tidak. Renungan bersifat pribadi secara default. Kamu yang memilih apakah ingin membagikannya ke ketua atau kelompok.",
      },
      {
        q: "Bagaimana cara memulai untuk komunitas kami?",
        a: "Masuk sebagai admin, buat program dan kelompok, undang ketua, lalu bagikan akses ke anggota. Jadwal baca dapat langsung digunakan bersama.",
      },
      {
        q: "Apakah ini aplikasi absensi spiritual?",
        a: "Bukan. Ringkasan partisipasi ditampilkan untuk merawat program — agar saling menguatkan, bukan mengawasi.",
      },
    ],
    finalCtaTitle: "Mulai hari ini",
    finalCtaSubtitle: "Masuk untuk melanjutkan bersama kelompokmu.",
    ctaDemo: "Coba demo",
    ctaAuth: "Masuk atau daftar",
    ctaAdmin: "Masuk sebagai Admin",
  },

  home: {
    eyebrow: "Beranda",
    greeting: (name: string) => `Shalom, ${name}`,
    subtitle: "Lanjutkan bacaan hari ini, lalu luangkan waktu untuk merenung.",
    subtitleDone: "Bacaan hari ini selesai. Mau menulis renungan?",
    subtitleLeader: "Lihat perjalanan kelompokmu, lalu lanjutkan bacaanmu.",
    todayReading: "Bacaan hari ini",
    tomorrowReading: "Bacaan besok",
    tomorrowHint: "Boleh dibaca lebih awal — jadwal tetap menunggu besok.",
    readTomorrow: "Baca bacaan besok",
    todayHint: (title: string) =>
      `${title} — baca Firman, lalu tulis apa yang berbicara padamu.`,
    continueReading: "Lanjut baca",
    openTodaysReading: "Lanjut baca hari ini",
    /** CTA utama kartu bacaan di beranda. */
    readTodayCta: "Baca hari ini",
    writeReflection: "Tulis refleksi",
    missedDaysLabel: (count: number) =>
      count === 1 ? "1 hari terlewat" : `${count} hari terlewat`,
    missedDaysHint: (count: number) =>
      count === 1
        ? "Ada 1 hari bacaan yang belum kamu selesaikan — kejar lewat jadwal."
        : `Ada ${count} hari bacaan yang belum kamu selesaikan — kejar lewat jadwal.`,
    missedDaysCta: "Kejar di jadwal",
    viewReflection: "Lihat refleksi",
    readFullInBible: "Baca pasal lengkap",
    readFullHint: "Pasal lengkap dan navigasi ayat tersedia di menu Baca.",
    encouragement:
      "Firman-Nya setia setiap hari. Kelompokmu berjalan bersama.",
    dailyFactEyebrow: "Fakta kisah hari ini",
    dailyFactCta: "Baca di Alkitab",
    groupJourney: (pct: number) =>
      `Kelompokmu telah menyelesaikan ${pct}% bacaan hari ini.`,
    recentActivity: "Aktivitas kelompok",
    communityReflections: {
      title: "Refleksi komunitas",
      subtitle: "Tulisan dari anggota di berbagai kelompok — saling menguatkan.",
      empty: "Belum ada refleksi yang dibagikan.",
    },
    timeline: {
      title: "Timeline",
      subtitle:
        "Bagikan bebas, saling menguatkan. Refleksi diri juga otomatis muncul di sini.",
      placeholder: "Apa yang sedang kamu pikirkan?",
      post: "Posting",
      empty: "Belum ada postingan. Mulai bagikan sesuatu.",
      sortNewest: "Terbaru",
      sortPopular: "Terpopuler",
      sortAria: "Urutkan timeline",
      loadMore: "Muat lebih banyak",
      delete: "Hapus postingan",
      deleteTitle: "Hapus postingan?",
      deleteDescription:
        "Postingan akan hilang dari timeline. Tindakan ini tidak bisa dibatalkan.",
      deleteReflectionDescription:
        "Refleksi ini akan dihapus dari timeline dan dari bacaan terkait.",
      deleteConfirm: "Hapus",
      deleteCancel: "Batal",
      deleted: "Postingan dihapus",
      deletedReflection: "Refleksi dihapus dari timeline",
    },
    personalNotes: {
      title: "Renungan",
      description: "Ruang aman untuk refleksi. Kamu yang mengatur siapa yang dapat membaca.",
    },
    viewAllNotes: "Semua renungan",
    reminderAria: "Pengingat baca",
    openInBible: "Baca di Alkitab",
    progress: {
      today: "Hari ini",
      todayHint: "Seberapa jauh kelompokmu dalam bacaan hari ini.",
      todayPersonalHint: "Apakah kamu sudah menyelesaikan bacaan hari ini.",
      yearToDate: "Tahun ini",
      yearToDateHint: "Progress baca dari 1 Januari hingga hari ini.",
      yearToDatePersonalHint:
        "Progress bacamu dari 1 Januari hingga hari ini.",
      todayDone: "Selesai",
      todayNotYet: "Belum mulai",
      yearToDateDetail: (completed: number, total: number) =>
        `${completed} dari ${total} hari`,
    },
  },

  bible: {
    eyebrow: "Kitab Suci",
    title: "Alkitab",
    subtitle: "Pilih kitab dan pasal, baca Terjemahan Baru kapan saja.",
    pickerTitle: "Pilih bacaan",
    pickerDescription: "Mulai dari kitab dan pasal yang ingin kamu baca.",
    changePassage: "Pilih bacaan lain",
    browseBible: "Jelajahi kitab lain",
    browseHint: "Jelajahi seluruh Alkitab — pilih kitab dan pasal bebas.",
    offlineReady: "Bacaan jadwal disimpan di perangkat untuk dibuka lebih cepat.",
    bookGridTitle: "Kitab Alkitab",
    bookGridHint: "Pilih kitab, lalu pasal. Progress menunjukkan pasal yang sudah dibuka.",
    backToBooks: "Semua kitab",
    chaptersOpened: (opened: number, total: number) =>
      `${opened} dari ${total} pasal dibuka`,
    readButton: "Baca sekarang",
    openFromLink: "Membuka pasal…",
    markComplete: "Selesai baca",
    markCompleteDone: "Bacaan hari ini selesai",
    markCompleteDoneHint: "Lanjutkan dengan menulis renungan singkat.",
    confirmTitle: "Selesai baca?",
    confirmYes: "Simpan",
    confirmCancel: "Batal",
    confirmPlaceholder: "Tulis refleksi singkat…",
    confirmEarlyTitle: "Selesai baca besok?",
    oldTestament: "Perjanjian Lama",
    newTestament: "Perjanjian Baru",
    bookLabel: "Kitab",
    bookPlaceholder: "Pilih kitab",
    tabScripture: "Kitab",
    tabDevotional: "Renungan",
    tabReflection: "Refleksi diri",
    chapterLabel: "Pasal",
    chapterOption: (n: number) => `Pasal ${n}`,
    invalidChapter: "Pasal tidak valid.",
    verseLabel: "Ayat",
    versePlaceholder: "Semua ayat (opsional)",
    verseAll: "Semua ayat",
    verseSearchPlaceholder: "Cari ayat…",
    verseEmptySearch: "Ayat tidak ditemukan",
    invalidVerse: "Ayat tidak valid.",
    dateLabel: "Tanggal bacaan",
    datePlaceholder: "Pilih tanggal bacaan",
    dateSearchPlaceholder: "Cari tanggal, hari, atau pasal…",
    dateEmpty: "Tidak ada tanggal bacaan cocok.",
    dateUnscheduled: "Belum ada tanggal yang terdata",
    dateUnscheduledHint: "Pasal ini belum masuk jadwal baca.",
    missedDaysHint: (count: number) =>
      count === 1
        ? "Ada 1 hari terlewat — pilih tanggalnya untuk mengejar."
        : `Ada ${count} hari terlewat — pilih tanggalnya untuk mengejar.`,
    pickByBook: "Kitab",
    pickByDate: "Tanggal",
    pickModeAria: "Pilih lewat kitab atau tanggal bacaan",
    searchLabel: "Cari atau pilih",
    searchPlaceholder: "Nama kitab, pasal, tanggal, atau kata kunci…",
    searchEmpty: "Tidak ada hasil. Coba nama kitab, pasal, tanggal, atau kata lain.",
    searchHint: "Ketuk hasil untuk membuka pasal atau ayat.",
    searchBooks: "Kitab & pasal",
    searchDates: "Tanggal bacaan",
    searchVerses: "Ayat berisi kata kunci",
    searchVersesEmpty: "Belum ada ayat cocok. Coba kata lain atau buka pasal dulu.",
    searchLoading: "Mencari…",
    searchVerseOpen: "Buka ayat",
    readerSettingsTitle: "Pengaturan baca",
    readerSettingsHint: "Tema, ukuran huruf, filter, dan waktu baca.",
    readerSettingsTime: "Waktu baca",
    readerSettingsDisplay: "Tampilan",
    readerSettingsFilter: "Filter teks",
    readerToolbarShow: "Alat baca",
    readerToolbarHide: "Sembunyikan",
    readingTimerPause: "Jeda timer",
    readingTimerResume: "Lanjutkan timer",
    readingTimerReset: "Reset timer",
    readingTimerRunningHint:
      "Waktu baca berlangsung — berhenti otomatis saat refleksi disimpan",
    readingTimerPausedHint: "Timer dijeda — tekan play untuk melanjutkan",
    chapterNoteTitle: "Refleksi diri",
    chapterNotePlaceholder:
      "Tulis insight, doa, atau hal penting dari bacaan ini…",
    chapterNoteSave: "Simpan refleksi",
    chapterNoteClear: "Hapus",
    chapterNoteSaved: "Refleksi tersimpan",
    chapterNoteSavedTitle: "Refleksi tersimpan",
    chapterNoteSavedDescription:
      "Catatan pribadimu sudah disimpan untuk bacaan ini.",
    chapterNoteSavedOk: "Baik",
    chapterNoteCleared: "Refleksi dihapus",
    chapterNoteEmpty: "Belum ada refleksi untuk bacaan ini.",
    chapterNoteUpdated: (date: string) => `Diperbarui ${date}`,
  },

  schedule: {
    eyebrow: "Rencana baca",
    title: "Jadwal Baca",
    subtitle: "Lihat perjalanan bacamu. Hijau = selesai, lembut = belum dilanjutkan.",
    calendarTitle: "Kalender baca",
    calendarDescription: "Ketuk tanggal untuk melihat detail bacaan.",
    tabCalendar: "Kalender",
    tabList: "Daftar",
    tabBooks: "Kitab",
    viewToggleAria: "Pilih tampilan jadwal",
    listTitle: "Daftar bacaan",
    listDescription:
      "Centang untuk tandai selesai. Ketuk item untuk membuka detail.",
    listEmpty: "Belum ada bacaan terjadwal di daftar ini.",
    listEmptyFiltered: "Tidak ada bacaan yang cocok dengan filter ini.",
    listFilterAria: "Filter status bacaan",
    listFilterAll: "Semua",
    listFilterMissed: "Terlewat",
    listFilterCompleted: "Selesai",
    booksTitle: "Pilih kitab",
    booksDescription: "Lihat progress pasal dan buka kitab mana saja.",
    statsChaptersLabel: "Pasal sudah dibaca",
    statsChaptersUnit: "pasal",
    statsDaysDone: "Hari selesai",
    statsDaysMissed: "Belum dilanjutkan",
    statsDaysUnit: "hari",
    statsAvgPerBook: "Rata-rata / kitab",
    statsAvgUnit: "pasal",
    markComplete: "Selesai baca",
    unmarkComplete: "Batalkan tanda selesai",
    markIncomplete: "Tandai belum selesai",
    markCompleteDone: "Bacaan ditandai selesai",
    markIncompleteDone: "Tanda selesai dibatalkan",
    unfinishedDaysBadgeAria: (count: number) =>
      count === 1
        ? "1 hari bacaan belum selesai"
        : `${count} hari bacaan belum selesai`,
    confirmMarkTitle: "Tandai sudah baca?",
    confirmMarkDescription: (passage: string) =>
      `Bacaan ${passage} akan ditandai selesai. Yakin sudah membacanya?`,
    confirmMarkYes: "Ya, sudah baca",
    confirmUnmarkTitle: "Batalkan tanda selesai?",
    confirmUnmarkDescription: (passage: string) =>
      `Bacaan ${passage} akan kembali bertanda belum selesai. Yakin ingin mengubahnya?`,
    confirmUnmarkYes: "Ya, batalkan",
    confirmToggleCancel: "Batal",
    noSchedule: "Tidak ada bacaan pada tanggal ini.",
    openReading: "Buka bacaan",
    readEarly: "Baca lebih awal",
    upcomingHint:
      "Jadwal mendatang boleh dibaca sekarang. Progress tetap bisa ditandai kapan saja.",
    status: {
      completed: "Selesai",
      missed: "Belum dilanjutkan",
      today: "Hari ini",
      upcoming: "Mendatang",
      none: "—",
    },
  },

  reading: {
    reflectionPrompt: "Pertanyaan renungan",
    markComplete: "Tandai selesai dibaca",
    visualAnchorTitle: "Bayangkan adegan ini",
    visualAnchorChapter: "Kisah di pasal ini",
    visualAnchorBook: "Tokoh utama kitab ini",
    visualAnchorHint:
      "Lihat gambar sebentar sebelum lanjut baca — membantu otak fokus dan mengingat konteks.",
    visualAnchorStoryCta: "Lihat kisah lengkap",
    visualAnchorCharacterCta: "Kenal tokohnya",
    devotional: {
      title: "Renungan",
      description: "Ringkasan dan refleksi dari pasal yang kamu baca.",
      badge: "Otomatis",
      retry: "Muat ulang",
      tabBody: "Renungan",
      tabKeyVerse: "Ayat kunci",
      tabQuestions: "Pertanyaan",
      keyVerseLabel: "Ayat kunci",
      prayerLabel: "Doa singkat",
      questionsTitle: "Pertanyaan renungan",
      studyLinksTitle: "Belajar lebih dalam",
      studyLinksSubtitle:
        "3 sumber di internet untuk memperdalam renungan pasal ini.",
    },
  },

  journal: {
    eyebrow: "Ruangan pribadi",
    title: "Jurnal Perasaan",
    subtitle:
      "Canvas bebas seperti Figma — geser, ubah ukuran, putar, dan susun teks, stiker, dan foto sesuka hati.",
    newPage: "Halaman baru",
    myPages: "Halaman jurnal",
    pageCount: (count: number) =>
      count === 1 ? "1 halaman" : `${count} halaman`,
    emptyTitle: "Belum ada halaman jurnal",
    emptyHint:
      "Mulai halaman pertama untuk mencatat perasaan, doa, atau momen hari ini.",
    untitledPage: "Tanpa judul",
    emptyPagePreview: "Halaman kosong — ketuk untuk menulis…",
    backToJournal: "Kembali ke jurnal",
    pageLabel: "halaman jurnal",
    titlePlaceholder: "Judul halaman…",
    writePlaceholder: "Tulis perasaan, doa, atau cerita hari ini…",
    save: "Simpan",
    saving: "Menyimpan…",
    autoSaved: "Tersimpan otomatis",
    savedToast: "Jurnal tersimpan",
    deleteTitle: "Hapus halaman jurnal?",
    deleteDescription:
      "Semua lembar, teks, stiker, dan foto di halaman ini akan dihapus permanen. Tindakan ini tidak bisa dibatalkan.",
    deleteCancel: "Batal",
    deleteConfirm: "Hapus halaman",
    deletedToast: "Halaman jurnal dihapus",
    toolSelect: "Pilih",
    toolText: "Teks",
    toolMood: "Perasaan",
    toolColor: "Latar",
    paperColorTitle: "Warna kertas",
    paperTypeTitle: "Jenis kertas",
    toolSticker: "Stiker",
    toolPhoto: "Foto",
    toolYoutube: "Lagu",
    layersTitle: "Layer",
    layersEmpty: "Kosong — tambahkan teks, stiker, atau foto di lembar aktif.",
    propertiesTitle: "Properti",
    layerText: "Teks",
    layerImage: "Foto",
    resizeHandle: "Ubah ukuran",
    rotateHandle: "Putar",
    rotateHandleHint: "Drag ikon putar di atas elemen · Shift = snap 15°",
    rotateLeft: "Putar kiri",
    rotateRight: "Putar kanan",
    rotationLabel: "Rotasi",
    resetRotation: "Reset",
    sizeLabel: "Ukuran",
    widthLabel: "Lebar",
    heightLabel: "Tinggi",
    fontLabel: "Jenis huruf",
    imageAdded: "Foto ditambahkan",
    imageError: "Gagal menambahkan foto",
    editorHint:
      "Alat Pilih: geser & ubah ukuran elemen. Ketuk lembar kiri/kanan untuk fokus. Alat Teks: ketuk canvas untuk kotak teks baru. Tambah lembar untuk bukaan baru.",
    enterFullscreen: "Layar penuh",
    exitFullscreen: "Keluar layar penuh",
    fullscreenLabel: "Mode layar penuh",
    toolVerse: "Ayat",
    newFromSchedule: "Dari jadwal baca",
    scheduleLinked: "Terhubung ke jadwal",
    verseSheetTitle: "Ayat & jadwal baca",
    verseSheetHint: "Masukkan ayat pilihan atau mulai jurnal dari bacaan harian.",
    verseTabSchedule: "Jadwal baca",
    verseTabPicker: "Pilih ayat",
    verseScheduleLabel: "Pilih hari baca",
    verseSchedulePlaceholder: "Cari tanggal atau pasal…",
    verseScheduleEmpty: "Belum ada bacaan terjadwal untuk tanggal ini.",
    verseApplySchedule: "Mulai jurnal dari jadwal",
    verseApplyScheduleWithText: "Jadwal + ayat bacaan",
    verseInsertPassageOnly: "Masukkan ayat bacaan saja",
    verseBookLabel: "Kitab",
    verseChapterLabel: "Pasal",
    verseChapterPrefix: "Pasal ",
    verseStartLabel: "Ayat awal",
    verseEndLabel: "Ayat akhir",
    verseNumberPrefix: "",
    versePreview: "Pratinjau ayat",
    verseInsert: "Masukkan ke jurnal",
    verseInserted: "Ayat ditambahkan ke jurnal",
    addToJournal: "Tambah ke jurnal",
    verseAddedFromReader: "Ayat dari bacaan ditambahkan ke jurnal",
    writeFromReading: "Tulis jurnal",
    noReadingForDate: "Tidak ada bacaan terjadwal untuk tanggal ini",
    verseInvalid: "Pilihan ayat tidak valid",
    verseLoadEmpty: "Ayat tidak ditemukan — coba pasal lain",
    verseLoadError: "Gagal memuat ayat",
    layerVerse: "Ayat",
    layerYoutube: "Lagu YouTube",
    youtubeSheetTitle: "Lampirkan lagu YouTube",
    youtubeSheetHint: "Tempel link video YouTube untuk diputar langsung di halaman jurnal.",
    youtubeUrlLabel: "Link YouTube",
    youtubeUrlPlaceholder: "https://youtube.com/watch?v=…",
    youtubeTitleLabel: "Judul lagu (opsional)",
    youtubeTitlePlaceholder: "Mis. Amazing Grace",
    youtubeUntitled: "Lagu tanpa judul",
    youtubeAttach: "Lampirkan ke jurnal",
    youtubeInvalid: "Link YouTube tidak valid",
    youtubeAdded: "Lagu ditambahkan ke jurnal",
    addSpread: "Tambah lembar",
    spreadAdded: "Lembar baru ditambahkan",
    spreadLabel: (current: number, total: number) => `Bukaan ${current} / ${total}`,
    prevSpread: "Bukaan sebelumnya",
    nextSpread: "Bukaan berikutnya",
    zoomIn: "Perbesar buku",
    zoomOut: "Perkecil buku",
    zoomReset: "Reset zoom",
    zoomLabel: (percent: number) => `${percent}%`,
    sheetLeft: "Kiri",
    sheetRight: "Kanan",
    emptySheet: "Lembar kosong",
  },

  transcribe: {
    eyebrow: "Alat bantu",
    title: "Live Transkrip",
    subtitle:
      "Transkrip khotbah atau ibadah langsung — termasuk bahasa daerah seperti Simalungun, dengan terjemahan ke Indonesia.",
    modeLabel: "Pilih mode",
    modeFastId: "Indonesia (cepat)",
    modeFastIdHint:
      "Langsung di browser. Cocok untuk khotbah Bahasa Indonesia. Pakai Chrome atau Edge.",
    modeFastEn: "English (cepat)",
    modeFastEnHint: "Transkrip langsung untuk khotbah berbahasa Inggris.",
    modeRegional: "Bahasa daerah",
    modeRegionalHint:
      "Untuk Simalungun, Karo, dll. Audio diproses per ~8 detik lalu diterjemahkan ke Indonesia. Butuh OPENAI_API_KEY.",
    checking: "Memeriksa…",
    aiReady: "AI siap",
    aiMissing: "Butuh API key",
    start: "Mulai dengarkan",
    stop: "Berhenti",
    upload: "Unggah rekaman",
    clear: "Hapus",
    copy: "Salin",
    copied: "Tersalin",
    fastListening: "Mendengarkan… bicara dekat mikrofon.",
    regionalListening:
      "Mendengarkan… teks muncul setiap ±8 detik. Dekatkan HP ke speaker.",
    regionalProcessing: "Memproses potongan audio…",
    transcriptTitle: "Transkrip",
    translationTitle: "Terjemahan Indonesia",
    translationEmpty:
      "Terjemahan muncul di sini setiap potongan audio selesai diproses.",
    empty:
      "Belum ada transkrip. Tekan “Mulai dengarkan” atau unggah rekaman khotbah.",
    tipsTitle: "Tips",
    tips: [
      "Mode cepat paling akurat di Chrome / Edge desktop.",
      "Untuk bahasa daerah, posisikan mikrofon dekat speaker gereja.",
      "Hasil Simalungun masih eksperimental — baca terjemahan Indonesia sebagai panduan.",
    ],
    webSpeechUnsupported:
      "Browser ini belum mendukung transkrip cepat. Coba Chrome atau Edge.",
    micDenied: "Akses mikrofon ditolak. Izinkan mikrofon lalu coba lagi.",
    whisperMissing:
      "Mode bahasa daerah butuh OPENAI_API_KEY di .env.local, lalu restart npm run dev.",
    errorGeneric: "Gagal mentranskrip. Coba lagi.",
  },

  profile: {
    eyebrow: "Akun",
    title: "Profil",
    subtitle: "Atur akun, pengingat, dan preferensimu.",
    rolePreview: {
      title: "Preview peran",
      description: "Lihat tampilan aplikasi sebagai anggota atau ketua kelompok.",
      member: {
        label: "Anggota",
        description: "Fokus baca, renung, dan perjalanan kelompok.",
      },
      leader: {
        label: "Ketua",
        description: "Dampingi kelompok dengan dorongan yang hangat.",
      },
    },
    leaderBanner: "Mode Ketua aktif — dampingi perjalanan kelompokmu.",
    group: {
      titleMember: "Kelompok baca",
      titleLeader: "Kelompok yang kamu dampingi",
      avgProgress: "Perjalanan kelompok",
      readToday: "Sudah baca hari ini",
      needsAttention: "Perlu perhatian",
      viewMembers: "Lihat anggota",
      viewMembersLeader: "Lihat anggota",
      sendReminder: "Kirim pengingat",
    },
    reminder: {
      title: "Pengingat harian",
      description:
        "Pengingat lembut dikirim setiap hari pada jam yang kamu pilih — via email, WhatsApp, atau keduanya.",
      timeLabel: "Jam pengingat",
      channelLabel: "Saluran pengingat",
      channelEmail: "Email",
      channelWhatsapp: "WhatsApp",
      channelBoth: "Email & WhatsApp",
      save: "Simpan",
    },
    access: {
      title: "Lainnya",
      admin: "Panel admin",
      logout: "Keluar",
    },
    roleBadge: (role: string) => {
      const labels: Record<string, string> = {
        admin: "Admin",
        leader: "Ketua",
        member: "Anggota",
      };
      return `Peran: ${labels[role] ?? role}`;
    },
  },

  leader: {
    panel: "Panel Ketua",
    snapshot: "Perjalanan kelompok hari ini",
    readTodayLabel: "Partisipasi hari ini",
    readTodayHint: "Persentase anggota yang sudah menyelesaikan bacaan hari ini.",
    yearToDateLabel: "Perjalanan tahun ini",
    yearToDateHint: "Rata-rata progress baca kelompok dari 1 Januari hingga hari ini.",
    yearToDateDetail: "Rata-rata kelompok tahun ini",
    avg14: "Rata-rata 14 hari",
    totalMembers: "Total anggota",
    readToday: "Sudah baca",
    pending: "Belum",
    missed: "Belum lanjut",
    viewAll: "Lihat perjalanan kelompok",
    todayTarget: "Perjalanan kelompok hari ini",
    todayTargetHint: "Seberapa jauh kelompokmu dalam bacaan hari ini.",
    todayPassage: "Pasal hari ini",
    membersRead: "anggota sudah baca",
    achieved: (pct: number) => `${pct}% perjalanan`,
    needsReminder: (count: number) =>
      `${count} anggota dapat diberi pengingat`,
    encourageHint: "Dorong dengan hangat — bukan teguran.",
    allDone: "Semua anggota sudah menyelesaikan bacaan hari ini.",
    roleCard: {
      title: "Peran kamu",
      memberHint: "Akses fitur sesuai peran di kelompok.",
      leaderHint: "Dampingi progress anggota dan kirim pengingat bila perlu.",
      watchMembers: "Lihat anggota",
      viewGroup: "Lihat kelompok",
    },
  },

  members: {
    title: "Anggota kelompok",
    titleLeader: "Anggota kelompok",
    subtitle: (group: string) => `Perjalanan bersama di ${group}.`,
    subtitleLeader: (group: string) =>
      `Dampingi perjalanan baca di ${group}.`,
    subtitleMulti: "Lihat perjalanan bacaan anggota kelompokmu.",
    subtitleMultiLeader: "Lihat perjalanan bacaan setiap anggota.",
    backToProfil: "Kembali ke profil",
    backToGroup: "Kembali ke kelompok",
    backToList: "Kembali ke anggota",
    remindShort: "Dorong",
    attentionTitle: "Perlu perhatian",
    attentionDescription: (count: number) =>
      `${count} anggota belum menyelesaikan bacaan hari ini.`,
    listTitle: "Anggota",
    summary: "Perjalanan kelompok",
    summaryHint: "Progress 14 hari terakhir",
    summaryHintLeader: "Progress 14 hari terakhir seluruh anggota",
    viewDetail: "Lihat detail",
    sendReminder: "Kirim pengingat",
    detail: {
      subtitle: "Perjalanan baca dan riwayat per hari.",
      last14: "14 hari terakhir",
      trendSummary: (completed: number, missed: number, pending: number) =>
        `${completed} selesai · ${missed} belum lanjut · ${pending} menunggu (7 hari)`,
      history: "Riwayat bacaan",
      historyHint: "Status baca per hari dalam periode ini.",
      seeMore: (count: number) => `Lihat ${count} lainnya`,
      seeLess: "Lebih sedikit",
      postsTitle: "Timeline & refleksi",
      postsSubtitle: "Postingan, refleksi, dan renungan yang dibagikan.",
      postsEmpty: "Belum ada postingan atau refleksi dari anggota ini.",
    },
    stats: {
      progress: "Progress",
      readProgress: "Progress baca",
      streak: "Beruntun",
      streakDays: (days: number) => `${days} hr`,
      completed: "Sudah baca",
      missed: "Belum lanjut",
      lastRead: (date: string) => `Terakhir baca: ${date}`,
      lastActive: (label: string) => `Terakhir aktif · ${label}`,
      neverRead: "Belum ada bacaan dalam periode ini",
      neverActive: "Belum pernah aktif",
    },
    summaryLabels: {
      avgRead: "Rata-rata baca",
      members: "Anggota",
      readToday: "Baca hari ini",
      pendingMissed: "Belum lanjut",
    },
    legend: {
      completed: "Sudah baca",
      missed: "Belum lanjut",
      pending: "Menunggu",
    },
    todayStatus: {
      completed: "Sudah baca hari ini",
      pending: "Belum baca hari ini",
      missed: "Belum dilanjutkan hari ini",
    },
    dayStatus: {
      completed: "Selesai",
      missed: "Belum lanjut",
      pending: "Menunggu",
    },
  },

  groups: {
    title: "Kelompok",
    subtitle: "Kita sedang menjalani perjalanan ini bersama.",
    leader: (name: string) => `Ketua: ${name}`,
    viewMembers: "Lihat anggota",
    tabOverview: "Ringkasan",
    tabProgress: "Progress",
    tabMembers: "Anggota",
    recentActivity: "Aktivitas terbaru",
    todayRead: "Baca hari ini",
    avg14Days: "Rata-rata bacaan",
    membersNeedAttention: (count: number) =>
      `${count} anggota perlu perhatian hari ini`,
    allOnTrack: "Semua on track hari ini",
    sendReminder: "Kirim pengingat",
    writeReflection: "Tulis refleksi",
    feedActivity: "Aktivitas",
    feedTimeline: "Timeline",
    todayPassage: "Bacaan hari ini",
    attentionCta: "Lihat anggota",
    progressTodaySummary: (done: number, total: number, pct: number) =>
      `Hari ini ${done}/${total} anggota sudah baca (${pct}%)`,
    journeyTitle: "Perjalanan bersama",
    todayParticipation: "Partisipasi hari ini",
    recentReflections: "Renungan terbaru",
    noReflections: "Belum ada renungan kelompok hari ini.",
    timelineTitle: "Timeline kelompok",
    timelineSubtitle:
      "Refleksi dan postingan anggota — saling menguatkan seperti feed bersama.",
    timelineEmpty: "Belum ada postingan di kelompok ini. Mulai bagikan refleksi.",
    timelinePlaceholder: "Bagikan refleksi atau kabar singkat ke kelompok…",
    programLabel: "Program",
    encouragement: "Saling mendukung — tanpa tekanan, tanpa ranking.",
    noGroupTitle: "Belum ada kelompok",
    noGroupHint:
      "Kamu mendaftar sebagai individu. Gabung kelompok kapan saja lewat kode undangan dari ketua.",
    noGroupCta: "Kembali ke beranda",
  },

  notes: {
    title: "Renungan",
    subtitle: "Tulis apa yang berbicara padamu — bagikan hanya jika kamu ingin.",
    today: "Renungan hari ini",
    history: "Riwayat renungan",
    updated: (date: string) => `Diperbarui ${date}`,
    prompt: "Apa yang paling berbicara padamu dari bacaan hari ini?",
    promptOptional: "Bagaimana kamu ingin menerapkannya dalam kehidupanmu?",
    placeholder:
      "Apa yang Tuhan taruh di hatimu? Tulis refleksi atau doa di sini…",
    privacy: "Default pribadi. Kamu yang memilih siapa yang dapat membaca.",
    save: "Simpan renungan",
    saved: "Tersimpan",
    visibility: {
      label: "Siapa yang dapat membaca",
      private: "Pribadi",
      privateHint: "Hanya kamu",
      leader: "Ketua saja",
      leaderHint: "Kamu dan ketua kelompok",
      group: "Kelompok",
      groupHint: "Semua anggota kelompok",
    },
    afterComplete: "Bacaan selesai. Luangkan waktu singkat untuk merenung.",
  },

  myReflections: {
    eyebrow: "Catatan pribadi",
    title: "Refleksiku",
    subtitle: "Yang kamu tulis setelah baca — tersimpan di perangkatmu.",
    write: "Tulis refleksi",
    empty: "Belum ada refleksi",
    emptyHint:
      "Setelah baca, catat apa yang berbicara padamu. Nanti muncul di sini.",
  },

  notifications: {
    title: "Notifikasi",
    subtitle: "Pengingat, dorongan, dan kabar dari kelompokmu.",
    empty: "Belum ada notifikasi baru.",
    emptyHint: "Pengingat baca dan dorongan dari ketua akan muncul di sini.",
    emptyFilter: "Tidak ada notifikasi di kategori ini.",
    emptyFilterHint: "Coba pilih kategori lain atau lihat semua notifikasi.",
    filterAll: "Semua",
    filterAria: "Filter kategori notifikasi",
    types: {
      reminder: "Pengingat baca",
      encouragement: "Dorongan",
      announcement: "Pengumuman kelompok",
      reflection: "Renungan baru",
    },
  },

  auth: {
    google: {
      continue: "Lanjutkan dengan Google",
      loading: "Mengalihkan ke Google…",
      divider: "atau",
    },
    login: {
      title: "Masuk",
      description: "Gunakan akun komunitasmu untuk melanjutkan bacaan hari ini.",
      submit: "Masuk",
      loading: "Sedang masuk…",
      error: "Username atau password salah. Silakan coba lagi.",
      rememberMe: "Ingat saya",
      forgotPassword: "Lupa password?",
      noAccount: "Belum punya akun?",
      register: "Daftar",
    },
    forgotPassword: {
      title: "Lupa password",
      description:
        "Masukkan username atau email akunmu. Untuk demo, kamu bisa langsung atur password baru.",
      submit: "Lanjut",
      loading: "Memeriksa akun…",
      backToLogin: "Kembali ke masuk",
      notFound:
        "Jika akun terdaftar, instruksi reset akan dikirim. Coba lagi atau hubungi admin komunitas.",
      resetTitle: "Atur password baru",
      resetDescription: (name: string) =>
        `Akun ${name} ditemukan. Masukkan password baru untuk demo ini.`,
      newPassword: "Password baru",
      confirmPassword: "Ulangi password baru",
      resetSubmit: "Simpan password baru",
      resetLoading: "Menyimpan…",
      mismatch: "Password tidak cocok.",
      tooShort: "Password minimal 6 karakter.",
      success: "Password berhasil diperbarui. Silakan masuk.",
      goLogin: "Masuk sekarang",
    },
    register: {
      title: "Buat akun",
      description: "Pilih cara bergabung — individu atau bareng kelompok.",
      submit: "Buat akun",
      loading: "Membuat akun…",
      error: "Pendaftaran gagal. Periksa data atau coba lagi.",
      emailTaken: "Email sudah terdaftar. Coba masuk atau gunakan email lain.",
      hasAccount: "Sudah punya akun?",
      login: "Masuk",
      membershipLabel: "Cara bergabung",
      membershipIndividual: "Individu",
      membershipIndividualHint:
        "Baca sendiri dengan jadwal pribadi. Bisa gabung kelompok nanti.",
      membershipGroup: "Punya kelompok",
      membershipGroupHint:
        "Setelah daftar, kamu akan diminta memasukkan kode undangan dari ketua kelompok.",
      next: "Lanjut",
      inviteStepTitle: "Masukkan kode undangan",
      inviteStepDescription:
        "Kode ini diberikan ketua kelompokmu. Setelah valid, akun langsung terhubung ke kelompok.",
      inviteCodeLabel: "Kode undangan",
      inviteCodePlaceholder: "Contoh: TG16",
      inviteCodeHint:
        "Tanya ketua kelompok jika belum punya kode. Huruf besar/kecil tidak masalah.",
      inviteCodeRequired: "Masukkan kode undangan kelompokmu.",
      inviteInvalid: "Kode undangan tidak dikenali.",
      inviteGroupPreview: (groupName: string) =>
        `Kamu akan bergabung ke ${groupName}.`,
      backToDetails: "Kembali",
    },
  },

  admin: {
    title: "Panel Admin",
    subtitle: "Pantau kesehatan program — untuk merawat, bukan mengawasi.",
    health: {
      title: "Kesehatan program",
      hint: "Ringkasan partisipasi dan keterlibatan komunitas.",
      participants: "Total peserta",
      activeReaders: "Pembaca aktif",
      completionRate: "Tingkat penyelesaian",
      weeklyActive: "Aktif minggu ini",
      reflections: "Partisipasi renungan",
      groupEngagement: "Keterlibatan kelompok",
    },
    schedule: {
      title: "Tambah bacaan harian",
      description:
        "Lihat seluruh jadwal program, atau tambahkan pasal untuk tanggal tertentu.",
      date: "Tanggal",
      passage: "Pasal Alkitab",
      passagePlaceholder: "Pilih satu atau lebih pasal",
      reflectionPrompt: "Pertanyaan refleksi",
      reflectionPlaceholder:
        "Apa yang paling berbicara padamu dari bacaan hari ini?",
      publish: "Terbitkan ke jadwal",
    },
    groups: {
      title: "Kelola kelompok",
      description: "Buat kelompok dalam program dan tentukan ketuanya.",
      name: "Nama kelompok",
      namePlaceholder: "Kelompok 01",
      leaderEmail: "Email ketua",
      leaderEmailPlaceholder: "ketua@example.com",
      create: "Buat kelompok",
    },
    program: {
      title: "Program baca",
      description:
        "Organisasi → Program → Kelompok. Satu organisasi dapat memiliki banyak program.",
      orgName: "Organisasi",
      orgPlaceholder: "Komunitas Kristen A",
      programName: "Nama program",
      programPlaceholder: "Bible Reading Journey 2027",
    },
  },

  adminCopy: {
    toolbarTitle: "Mode edit copy",
    toolbarHint:
      "Aktifkan mode edit, klik teks di halaman, lalu simpan. Perubahan berlaku di semua halaman.",
    toolbarEditing:
      "Klik teks yang disorot untuk mengedit langsung di halaman ini.",
    startEditing: "Edit copy",
    save: "Simpan",
    cancel: "Batal",
    reset: "Reset semua",
    resetConfirm:
      "Reset semua perubahan copy ke teks default? Tindakan ini tidak bisa dibatalkan.",
    saved: "Copy berhasil disimpan",
    saveFailed: "Gagal menyimpan copy. Coba lagi.",
    resetDone: "Copy direset ke default",
    resetFailed: "Gagal mereset copy",
    editingActive: "Mode edit aktif — teks yang bisa diedit disorot",
  },
} as const;
