/** Teks UI — profesional, to the point, tetap hangat. */
export const copy = {
  app: {
    name: "Baca Alkitab Bersama",
    metaDescription:
      "Platform baca Alkitab untuk komunitas: jadwal harian, kelompok, dan ruang renungan yang aman.",
  },

  nav: {
    home: "Beranda",
    read: "Baca Alkitab",
    explore: "Explore",
    schedule: "Jadwal Baca",
    notes: "Renungan",
    myReflections: "Refleksiku",
    chat: "Chat",
    group: "Kelompokku",
    myGroup: "Kelompokku",
    features: "Fitur",
    notifications: "Notifikasi",
    profile: "Profil",
  },

  explore: {
    eyebrow: "Belajar lebih dalam",
    title: "Explore",
    subtitle:
      "Sejarah kitab, topik Firman, tokoh Alkitab, glosarium, peta, dan silsilah Yesus — semua pintu masuk untuk mengenal Alkitab lebih utuh.",
    hint: "Pilih satu jalur belajar. Kamu bisa kembali ke sini kapan saja dari menu Explore.",
    backToExplore: "Explore",
  },

  chat: {
    title: "Chat kelompok",
    subtitle: "Ruang percakapan kelompok — saling menguatkan.",
    lockedTitle: "Belum ada refleksi hari ini",
    lockedHint:
      "Tulis refleksi bacaan di bawah — otomatis masuk ke chat kelompok.",
    writeToUnlock: "Tulis refleksi",
    placeholder: "Tulis pesan… ketik @ untuk mention (@all untuk semua)",
    reflectionPlaceholder:
      "Tulis refleksi dari bacaanmu… langsung terkirim ke chat kelompok",
    composerModeAria: "Jenis pesan",
    composerModeReflection: "Refleksi",
    composerModeChat: "Chat",
    reflectionSentToast: "Refleksi terkirim ke chat kelompok",
    send: "Kirim",
    empty: "Belum ada pesan. Mulai percakapan dengan kelompokmu.",
    mentionLabel: "Mention anggota",
    mentionEmpty: "Tidak ada anggota yang cocok",
    mentionAll: "Semua anggota",
    mentionAllHandle: "@all",
    delete: "Hapus",
    deleteTitle: "Hapus pesan?",
    deleteDescription:
      "Isi pesan diganti tanda “pesan dihapus” di chat kelompok. Hanya bisa dalam 15 menit setelah dikirim.",
    deleteConfirm: "Hapus pesan",
    deleteCancel: "Batal",
    deleteSuccess: "Pesan dihapus",
    deleteExpired: "Pesan hanya bisa dihapus dalam 15 menit setelah dikirim.",
    deleteWindowHint: "Bisa dihapus",
    deletedPlaceholder: "Pesan ini dihapus",
    deletedReflectionPlaceholder: "Refleksi ini dihapus",
    reflectionBadge: "Refleksi bacaan",
    reflectionShared: "Membagikan refleksi",
    messageBadge: "Chat",
    legendReflection: "Refleksi",
    legendChat: "Chat biasa",
    filterAria: "Filter isi chat",
    filterAll: "Semua",
    filterReflection: "Refleksi",
    filterChat: "Chat biasa",
    filterEmptyReflection: "Belum ada refleksi bacaan di chat ini.",
    filterEmptyChat: "Belum ada chat biasa.",
    emojiAria: "Pilih emoji",
    gifAria: "Cari & kirim GIF",
    gifSearchPlaceholder: "Cari GIF… atau tempel tautan https",
    gifEmpty: "Tidak ada GIF. Coba kata lain atau tempel tautan.",
    gifLoading: "Memuat GIF…",
    gifSourceHint: "Sumber: Giphy / Tenor / tautan",
    gifRemove: "Hapus GIF",
    gifPreview: "Pratinjau GIF",
  },

  read: {
    title: "Baca",
    hint: "Mulai dari bacaan hari ini. Jadwal lengkap ada di bawah.",
    tabBible: "Hari ini",
    tabSchedule: "Jadwal",
  },

  topics: {
    eyebrow: "Jelajahi Alkitab",
    title: "Topik Firman",
    subtitle:
      "Puluhan tema Firman — kasih, ketakutan, doa, kerja, keselamatan, dan lainnya. Baca ayat kunci, lalu lanjut ke konteks pasal.",
    searchPlaceholder: "Cari topik, misalnya kasih atau ketakutan…",
    categoryAria: "Kategori topik",
    featured: "Populer untuk memulai",
    allTopics: "Semua topik",
    results: "Hasil pencarian",
    emptySearch: "Tidak ada topik yang cocok. Coba kata lain.",
    catalogCount: (count: number) => `${count} topik siap dijelajahi`,
    keyVerses: "Ayat kunci",
    explanationTitle: "Penjelasan",
    reflectionTitle: "Renungan",
    prayerTitle: "Doa",
    relatedTitle: "Topik terkait",
    readInContext: "Baca di konteks",
    contextHint:
      "Ayat kunci adalah pintu masuk. Baca pasal lengkapnya supaya konteksnya utuh.",
    backToRead: "Kembali ke Baca",
    backToTopics: "Semua topik",
    openCta: "Jelajahi topik",
  },

  glossary: {
    eyebrow: "Kamus singkat",
    title: "Glosarium",
    subtitle:
      "Puluhan istilah Alkitab — anugerah, Paskah, Golgota, Roh Kudus, dan lainnya — dijelaskan dengan bahasa sehari-hari.",
    searchPlaceholder: "Cari istilah, misalnya anugerah atau Sabat…",
    categoryAria: "Kategori istilah",
    featured: "Sering ditanyakan",
    allTerms: "Semua istilah",
    results: "Hasil pencarian",
    emptySearch: "Tidak ada istilah yang cocok. Coba kata lain.",
    catalogCount: (count: number) => `${count} istilah siap dicari`,
    explanation: "Penjelasan",
    keyVerse: "Ayat pintu masuk",
    readInContext: "Baca di konteks",
    hint: "Ini pengantar singkat, bukan kamus teologi lengkap. Baca ayat di konteks pasalnya supaya maknanya utuh.",
    backToRead: "Kembali ke Baca",
    backToList: "Semua istilah",
    openCta: "Glosarium",
  },

  characters: {
    eyebrow: "Kenali tokohnya",
    title: "Tokoh Alkitab",
    subtitle:
      "Latar hidup, kisah mendalam, momen kunci, pelajaran, renungan, doa, dan ayat — kenali tokoh Alkitab lebih utuh.",
    searchPlaceholder: "Cari tokoh, misalnya Daud, Rahab, atau Ayub…",
    categoryAria: "Kategori tokoh",
    featured: "Sering dicari",
    allCharacters: "Semua tokoh",
    results: "Hasil pencarian",
    emptySearch: "Tidak ada tokoh yang cocok. Coba nama lain.",
    catalogCount: (count: number) => `${count} tokoh siap dikenal`,
    backgroundTitle: "Latar & konteks",
    storyTitle: "Kisah hidup",
    momentsTitle: "Momen kunci",
    lessonsTitle: "Pelajaran untuk kita",
    reflectionTitle: "Renungan",
    prayerTitle: "Doa singkat",
    keyVerse: "Ayat pintu masuk",
    keyVerses: "Ayat-ayat kunci",
    relatedTitle: "Tokoh terkait",
    readInContext: "Baca di konteks",
    hint: "Profil ini membantu mengenal tokohnya. Baca pasal terkait supaya kisahnya utuh dalam konteks Alkitab.",
    backToRead: "Kembali ke Baca",
    backToList: "Semua tokoh",
    openCta: "Tokoh Alkitab",
  },

  places: {
    eyebrow: "Peta zaman dulu",
    title: "Peta Alkitab",
    subtitle:
      "Betlehem, Mesir, Yerusalem, Babel, dan lainnya — lihat di Google Maps, ketuk pin untuk kisah yang terjadi di sana.",
    searchPlaceholder: "Cari tempat atau kisah, misalnya Betlehem…",
    regionAria: "Wilayah peta",
    kindAria: "Jenis tempat",
    kindLabel: "Jenis",
    regionLabel: "Wilayah",
    allKinds: "Semua jenis",
    featured: "Tempat yang sering dibaca",
    allPlaces: "Semua tempat",
    results: "Hasil pencarian",
    emptySearch: "Tidak ada tempat yang cocok. Coba kata lain.",
    catalogCount: (places: number, stories: number) =>
      `${places} tempat · ${stories} kisah`,
    storiesTitle: "Kisah di tempat ini",
    readInContext: "Baca di konteks",
    backToRead: "Kembali ke Baca",
    backToList: "Semua tempat",
    backToMap: "Kembali ke peta",
    openCta: "Peta Alkitab",
    mapHint:
      "Pin menandai perkiraan lokasi modern dari tempat Alkitab. Pakai tombol Ukur jarak, lalu ketuk dua pin untuk melihat jaraknya (bukan batas politik zaman dulu).",
    hint: "Setiap kisah adalah pintu masuk. Baca pasal lengkapnya supaya konteksnya utuh.",
  },

  genealogy: {
    eyebrow: "Dari awal sampai penggenapan",
    title: "Silsilah Adam → Yesus",
    subtitle:
      "Peta garis keturunan menurut Lukas 3 — dari Adam sampai Yesus, dengan catatan jalur Matius dari Daud.",
    searchPlaceholder: "Cari nama, misalnya Abraham atau Zerubabel…",
    catalogCount: (count: number) => `${count} generasi dalam garis Lukas`,
    featured: "Tokoh kunci",
    matthewBranch: "Lihat cabang Matius (lewat Salomo)",
    matthewNote:
      "Matius 1 menempuh jalur raja dari Daud melalui Salomo. Lukas 3 menempuh jalur melalui Natan. Keduanya bertemu lagi pada Yesus.",
    readInContext: "Baca di konteks",
    openCharacter: "Profil tokoh",
    emptySearch: "Tidak ada nama yang cocok. Coba kata lain.",
    hint: "Ini peta belajar berdasarkan Lukas 3:23–38. Beberapa ejaan dan urutan mengikuti tradisi teks yang dipakai terjemahan; bandingkan dengan Matius 1 untuk jalur lain dari Daud.",
    backToRead: "Kembali ke Baca",
    openCta: "Silsilah",
  },

  bookIntro: {
    eyebrow: "Kenali kitabnya",
    title: "Sejarah Kitab",
    subtitle:
      "Isi kitab, tokoh, latar, tema, kerangka, dan sumber rujukan — pengantar tiap kitab Alkitab.",
    searchPlaceholder: "Cari kitab atau tokoh, misalnya Kejadian atau Paulus…",
    allBooks: "Semua",
    listTitle: "66 kitab",
    results: "Hasil pencarian",
    emptySearch: "Tidak ada kitab yang cocok. Coba nama lain.",
    overviewTitle: "Latar belakang",
    aboutTitle: "Kitab ini menceritakan tentang apa",
    themesTitle: "Tema utama",
    charactersTitle: "Tokoh yang terlibat",
    charactersHint: "Tokoh utama yang muncul atau berperan penting dalam kitab ini.",
    outlineTitle: "Kerangka besar",
    deeperTitle: "Pendalaman",
    notesTitle: "Catatan penafsiran",
    sourcesTitle: "Sumber rujukan",
    sourcesHint:
      "Teks ini sintesis ringkas untuk pembaca awam — bukan kutipan literal satu buku. Lihat daftar sumber di bawah.",
    chaptersLabel: "pasal",
    fields: {
      who: "Siapa yang menulis",
      when: "Kapan",
      how: "Bagaimana ditulis",
      why: "Mengapa ditulis",
      audience: "Untuk siapa",
    },
    readBook: "Baca kitab ini",
    backToRead: "Kembali ke Baca",
    backToList: "Semua kitab",
    openCta: "Sejarah kitab",
    aboutBook: "Tentang kitab",
    disclaimer:
      "Pengantar disusun dari tradisi gereja dan literatur pengantar Alkitab yang tercantum di sumber. Di beberapa kitab, atribusi/penanggalan akademis berbeda dari tradisi — itu dicatat di bagian catatan.",
  },

  worship: {
    title: "Lagu worship",
    toolbarHint: "Musik worship — ketuk buka, tahan untuk geser",
    hint: "Instrumental lembut biar lebih tenang baca Firman. Butuh koneksi YouTube. TTS berhenti otomatis saat musik diputar.",
    play: "Putar",
    stop: "Berhenti",
    close: "Tutup",
    minimize: "Perkecil",
    expand: "Perbesar",
    nowPlaying: "Sedang diputar",
    openYoutube: "Buka di YouTube",
    dragHint: "Tahan lalu geser",
    bubbleLabel: "Musik sedang diputar — ketuk untuk buka panel",
  },

  common: {
    comingSoon: "Segera hadir",
    comingSoonHint: "Fitur ini sedang disiapkan.",
    back: "Kembali",
    members: "anggota",
    days: "hari",
    you: "(kamu)",
    roles: {
      admin: "Admin",
      leader: "Ketua",
      member: "Anggota",
    },
  },

  landing: {
    heroLead: "Baca, renung, dan tumbuh",
    heroAccent: "bersama kelompokmu setiap hari.",
    subhero:
      "Baca Firman bersama komunitas — dengan jadwal yang jelas dan dukungan yang hangat.",
    features: {
      schedule: {
        title: "Jadwal Baca",
        description: "Pasal dan renungan sudah siap. Buka, lalu mulai.",
      },
      group: {
        title: "Kelompok",
        description: "Baca bersama kelompok. Saling mendukung tanpa tekanan absensi.",
      },
      notes: {
        title: "Renungan pribadi",
        description: "Tulis refleksi. Bagikan hanya jika kamu ingin.",
      },
    },
    journeyTitle: "Tiga langkah yang sederhana",
    journeySubtitle: "Dari bacaan harian, ke refleksi pribadi, lalu dukungan kelompok.",
    journey: {
      read: {
        title: "Baca",
        description: "Ikuti jadwal harian. Pasal siap menunggu.",
      },
      reflect: {
        title: "Renung",
        description: "Catat yang berbicara padamu — tanpa tekanan untuk membagikan.",
      },
      grow: {
        title: "Tumbuh bersama",
        description: "Saling menguatkan di kelompok. Perjalanan, bukan absensi.",
      },
    },
    forWhomTitle: "Untuk komunitas yang ingin konsisten",
    forWhomSubtitle:
      "Gereja, kantor, youth, atau small group — satu program, banyak kelompok.",
    faqTitle: "Pertanyaan yang sering diajukan",
    faqSubtitle: "Jawaban singkat agar kamu tahu apa yang bisa diharapkan.",
    faq: [
      {
        q: "Apa itu Baca Alkitab Bersama?",
        a: "Platform baca Alkitab untuk komunitas: jadwal harian, kelompok kecil, dan ruang renungan yang aman — tanpa suasana absensi.",
      },
      {
        q: "Siapa yang dapat menggunakannya?",
        a: "Admin mengelola program, ketua mendampingi kelompok, dan anggota fokus membaca serta merenung. Cocok untuk gereja, youth, kantor, atau small group.",
      },
      {
        q: "Apakah renungan wajib dibagikan?",
        a: "Tidak. Renungan bersifat pribadi secara default. Kamu yang memilih apakah ingin membagikannya ke ketua atau kelompok.",
      },
      {
        q: "Bagaimana cara memulai untuk komunitas kami?",
        a: "Masuk sebagai admin, buat program dan kelompok, undang ketua, lalu bagikan akses ke anggota. Jadwal baca dapat langsung digunakan bersama.",
      },
      {
        q: "Apakah ini aplikasi absensi spiritual?",
        a: "Bukan. Ringkasan partisipasi ditampilkan untuk merawat program — agar saling menguatkan, bukan mengawasi.",
      },
    ],
    finalCtaTitle: "Mulai hari ini",
    finalCtaSubtitle: "Masuk untuk melanjutkan bersama kelompokmu.",
    ctaDemo: "Coba demo",
    ctaAuth: "Masuk atau daftar",
    ctaAdmin: "Masuk sebagai Admin",
  },

  home: {
    eyebrow: "Beranda",
    greeting: (name: string) => `Shalom, ${name}`,
    subtitle: "Lanjutkan bacaan hari ini, lalu luangkan waktu untuk merenung.",
    subtitleDone: "Bacaan hari ini selesai. Mau menulis renungan?",
    subtitleLeader: "Lihat perjalanan kelompokmu, lalu lanjutkan bacaanmu.",
    todayReading: "Bacaan hari ini",
    tomorrowReading: "Bacaan besok",
    tomorrowHint: "Boleh dibaca lebih awal — jadwal tetap menunggu besok.",
    readTomorrow: "Baca bacaan besok",
    todayHint: (title: string) =>
      `${title} — baca Firman, lalu tulis apa yang berbicara padamu.`,
    continueReading: "Lanjut baca",
    openTodaysReading: "Lanjut baca hari ini",
    /** CTA utama kartu bacaan di beranda. */
    readTodayCta: "Baca hari ini",
    writeReflection: "Tulis refleksi",
    viewReflection: "Lihat refleksi",
    readFullInBible: "Baca pasal lengkap",
    readFullHint: "Pasal lengkap dan navigasi ayat tersedia di menu Baca.",
    encouragement:
      "Firman-Nya setia setiap hari. Kelompokmu berjalan bersama.",
    dailyFactEyebrow: "Fakta kisah hari ini",
    dailyFactCta: "Baca di Alkitab",
    groupJourney: (pct: number) =>
      `Kelompokmu telah menyelesaikan ${pct}% bacaan hari ini.`,
    recentActivity: "Aktivitas kelompok",
    communityReflections: {
      title: "Refleksi komunitas",
      subtitle: "Tulisan dari anggota di berbagai kelompok — saling menguatkan.",
      empty: "Belum ada refleksi yang dibagikan.",
    },
    timeline: {
      title: "Timeline",
      subtitle:
        "Bagikan bebas, saling menguatkan. Refleksi diri juga otomatis muncul di sini.",
      placeholder: "Apa yang sedang kamu pikirkan?",
      post: "Posting",
      empty: "Belum ada postingan. Mulai bagikan sesuatu.",
      sortNewest: "Terbaru",
      sortPopular: "Terpopuler",
      sortAria: "Urutkan timeline",
      loadMore: "Muat lebih banyak",
      delete: "Hapus postingan",
      deleteTitle: "Hapus postingan?",
      deleteDescription:
        "Postingan akan hilang dari timeline. Tindakan ini tidak bisa dibatalkan.",
      deleteReflectionDescription:
        "Refleksi ini akan dihapus dari timeline dan dari bacaan terkait.",
      deleteConfirm: "Hapus",
      deleteCancel: "Batal",
      deleted: "Postingan dihapus",
      deletedReflection: "Refleksi dihapus dari timeline",
    },
    personalNotes: {
      title: "Renungan",
      description: "Ruang aman untuk refleksi. Kamu yang mengatur siapa yang dapat membaca.",
    },
    viewAllNotes: "Semua renungan",
    reminderAria: "Pengingat baca",
    openInBible: "Baca di Alkitab",
    progress: {
      today: "Hari ini",
      todayHint: "Seberapa jauh kelompokmu dalam bacaan hari ini.",
      todayPersonalHint: "Apakah kamu sudah menyelesaikan bacaan hari ini.",
      yearToDate: "Tahun ini",
      yearToDateHint: "Progress baca dari 1 Januari hingga hari ini.",
      yearToDatePersonalHint:
        "Progress bacamu dari 1 Januari hingga hari ini.",
      todayDone: "Selesai",
      todayNotYet: "Belum mulai",
      yearToDateDetail: (completed: number, total: number) =>
        `${completed} dari ${total} hari`,
    },
  },

  bible: {
    eyebrow: "Kitab Suci",
    title: "Alkitab",
    subtitle: "Pilih kitab dan pasal, baca Terjemahan Baru kapan saja.",
    pickerTitle: "Pilih bacaan",
    pickerDescription: "Mulai dari kitab dan pasal yang ingin kamu baca.",
    changePassage: "Pilih bacaan lain",
    browseBible: "Jelajahi kitab lain",
    browseHint: "Jelajahi seluruh Alkitab — pilih kitab dan pasal bebas.",
    offlineReady: "Bacaan jadwal disimpan di perangkat untuk dibuka lebih cepat.",
    bookGridTitle: "Kitab Alkitab",
    bookGridHint: "Pilih kitab, lalu pasal. Progress menunjukkan pasal yang sudah dibuka.",
    backToBooks: "Semua kitab",
    chaptersOpened: (opened: number, total: number) =>
      `${opened} dari ${total} pasal dibuka`,
    readButton: "Baca sekarang",
    openFromLink: "Membuka pasal…",
    markComplete: "Selesai baca",
    markCompleteDone: "Bacaan hari ini selesai",
    markCompleteDoneHint: "Lanjutkan dengan menulis renungan singkat.",
    confirmTitle: "Selesai baca?",
    confirmYes: "Simpan",
    confirmCancel: "Batal",
    confirmPlaceholder: "Tulis refleksi singkat…",
    confirmEarlyTitle: "Selesai baca besok?",
    oldTestament: "Perjanjian Lama",
    newTestament: "Perjanjian Baru",
    bookLabel: "Kitab",
    bookPlaceholder: "Pilih kitab",
    tabScripture: "Kitab",
    tabDevotional: "Renungan",
    tabReflection: "Refleksi diri",
    chapterLabel: "Pasal",
    chapterOption: (n: number) => `Pasal ${n}`,
    invalidChapter: "Pasal tidak valid.",
    verseLabel: "Ayat",
    versePlaceholder: "Semua ayat (opsional)",
    verseAll: "Semua ayat",
    verseSearchPlaceholder: "Cari ayat…",
    verseEmptySearch: "Ayat tidak ditemukan",
    invalidVerse: "Ayat tidak valid.",
    dateLabel: "Tanggal bacaan",
    datePlaceholder: "Pilih tanggal bacaan",
    dateSearchPlaceholder: "Cari tanggal, hari, atau pasal…",
    dateEmpty: "Tidak ada tanggal bacaan cocok.",
    dateUnscheduled: "Belum ada tanggal yang terdata",
    dateUnscheduledHint: "Pasal ini belum masuk jadwal baca.",
    missedDaysHint: (count: number) =>
      count === 1
        ? "Ada 1 hari terlewat — pilih tanggalnya untuk mengejar."
        : `Ada ${count} hari terlewat — pilih tanggalnya untuk mengejar.`,
    pickByBook: "Kitab",
    pickByDate: "Tanggal",
    pickModeAria: "Pilih lewat kitab atau tanggal bacaan",
    searchLabel: "Cari atau pilih",
    searchPlaceholder: "Nama kitab, pasal, tanggal, atau kata kunci…",
    searchEmpty: "Tidak ada hasil. Coba nama kitab, pasal, tanggal, atau kata lain.",
    searchHint: "Ketuk hasil untuk membuka pasal atau ayat.",
    searchBooks: "Kitab & pasal",
    searchDates: "Tanggal bacaan",
    searchVerses: "Ayat berisi kata kunci",
    searchVersesEmpty: "Belum ada ayat cocok. Coba kata lain atau buka pasal dulu.",
    searchLoading: "Mencari…",
    searchVerseOpen: "Buka ayat",
    chapterNoteTitle: "Refleksi diri",
    chapterNotePlaceholder:
      "Tulis insight, doa, atau hal penting dari bacaan ini…",
    chapterNoteSave: "Simpan refleksi",
    chapterNoteClear: "Hapus",
    chapterNoteSaved: "Refleksi tersimpan",
    chapterNoteSavedTitle: "Refleksi tersimpan",
    chapterNoteSavedDescription:
      "Catatan pribadimu sudah disimpan untuk bacaan ini.",
    chapterNoteSavedOk: "Baik",
    chapterNoteCleared: "Refleksi dihapus",
    chapterNoteEmpty: "Belum ada refleksi untuk bacaan ini.",
    chapterNoteUpdated: (date: string) => `Diperbarui ${date}`,
  },

  schedule: {
    eyebrow: "Rencana baca",
    title: "Jadwal Baca",
    subtitle: "Lihat perjalanan bacamu. Hijau = selesai, lembut = belum dilanjutkan.",
    calendarTitle: "Kalender baca",
    calendarDescription: "Ketuk tanggal untuk melihat detail bacaan.",
    tabCalendar: "Kalender",
    tabList: "Daftar",
    tabBooks: "Kitab",
    viewToggleAria: "Pilih tampilan jadwal",
    listTitle: "Daftar bacaan",
    listDescription:
      "Centang untuk tandai selesai. Ketuk item untuk membuka detail.",
    listEmpty: "Belum ada bacaan terjadwal di daftar ini.",
    listEmptyFiltered: "Tidak ada bacaan yang cocok dengan filter ini.",
    listFilterAria: "Filter status bacaan",
    listFilterAll: "Semua",
    listFilterMissed: "Terlewat",
    listFilterCompleted: "Selesai",
    booksTitle: "Pilih kitab",
    booksDescription: "Lihat progress pasal dan buka kitab mana saja.",
    statsChaptersLabel: "Pasal sudah dibaca",
    statsChaptersUnit: "pasal",
    statsDaysDone: "Hari selesai",
    statsDaysMissed: "Belum dilanjutkan",
    statsDaysUnit: "hari",
    statsAvgPerBook: "Rata-rata / kitab",
    statsAvgUnit: "pasal",
    markComplete: "Selesai baca",
    unmarkComplete: "Batalkan tanda selesai",
    markIncomplete: "Tandai belum selesai",
    markCompleteDone: "Bacaan ditandai selesai",
    markIncompleteDone: "Tanda selesai dibatalkan",
    confirmMarkTitle: "Tandai sudah baca?",
    confirmMarkDescription: (passage: string) =>
      `Bacaan ${passage} akan ditandai selesai. Yakin sudah membacanya?`,
    confirmMarkYes: "Ya, sudah baca",
    confirmUnmarkTitle: "Batalkan tanda selesai?",
    confirmUnmarkDescription: (passage: string) =>
      `Bacaan ${passage} akan kembali bertanda belum selesai. Yakin ingin mengubahnya?`,
    confirmUnmarkYes: "Ya, batalkan",
    confirmToggleCancel: "Batal",
    noSchedule: "Tidak ada bacaan pada tanggal ini.",
    openReading: "Buka bacaan",
    readEarly: "Baca lebih awal",
    upcomingHint:
      "Jadwal mendatang boleh dibaca sekarang. Progress tetap bisa ditandai kapan saja.",
    status: {
      completed: "Selesai",
      missed: "Belum dilanjutkan",
      today: "Hari ini",
      upcoming: "Mendatang",
      none: "—",
    },
  },

  reading: {
    reflectionPrompt: "Pertanyaan renungan",
    markComplete: "Tandai selesai dibaca",
    devotional: {
      title: "Renungan",
      description: "Ringkasan dan refleksi dari pasal yang kamu baca.",
      badge: "Otomatis",
      retry: "Muat ulang",
      tabBody: "Renungan",
      tabKeyVerse: "Ayat kunci",
      tabQuestions: "Pertanyaan",
      keyVerseLabel: "Ayat kunci",
      prayerLabel: "Doa singkat",
      questionsTitle: "Pertanyaan renungan",
      studyLinksTitle: "Belajar lebih dalam",
      studyLinksSubtitle:
        "3 sumber di internet untuk memperdalam renungan pasal ini.",
    },
  },

  profile: {
    eyebrow: "Akun",
    title: "Profil",
    subtitle: "Atur akun, pengingat, dan preferensimu.",
    rolePreview: {
      title: "Preview peran",
      description: "Lihat tampilan aplikasi sebagai anggota atau ketua kelompok.",
      member: {
        label: "Anggota",
        description: "Fokus baca, renung, dan perjalanan kelompok.",
      },
      leader: {
        label: "Ketua",
        description: "Dampingi kelompok dengan dorongan yang hangat.",
      },
    },
    leaderBanner: "Mode Ketua aktif — dampingi perjalanan kelompokmu.",
    group: {
      titleMember: "Kelompok baca",
      titleLeader: "Kelompok yang kamu dampingi",
      avgProgress: "Perjalanan kelompok",
      readToday: "Sudah baca hari ini",
      needsAttention: "Perlu perhatian",
      viewMembers: "Lihat anggota",
      viewMembersLeader: "Lihat anggota",
      sendReminder: "Kirim pengingat",
    },
    reminder: {
      title: "Pengingat harian",
      description:
        "Pengingat lembut dikirim setiap hari pada jam yang kamu pilih — via email, WhatsApp, atau keduanya.",
      timeLabel: "Jam pengingat",
      channelLabel: "Saluran pengingat",
      channelEmail: "Email",
      channelWhatsapp: "WhatsApp",
      channelBoth: "Email & WhatsApp",
      save: "Simpan",
    },
    access: {
      title: "Lainnya",
      admin: "Panel admin",
      logout: "Keluar",
    },
    roleBadge: (role: string) => {
      const labels: Record<string, string> = {
        admin: "Admin",
        leader: "Ketua",
        member: "Anggota",
      };
      return `Peran: ${labels[role] ?? role}`;
    },
  },

  leader: {
    panel: "Panel Ketua",
    snapshot: "Perjalanan kelompok hari ini",
    readTodayLabel: "Partisipasi hari ini",
    readTodayHint: "Persentase anggota yang sudah menyelesaikan bacaan hari ini.",
    yearToDateLabel: "Perjalanan tahun ini",
    yearToDateHint: "Rata-rata progress baca kelompok dari 1 Januari hingga hari ini.",
    yearToDateDetail: "Rata-rata kelompok tahun ini",
    avg14: "Rata-rata 14 hari",
    totalMembers: "Total anggota",
    readToday: "Sudah baca",
    pending: "Belum",
    missed: "Belum lanjut",
    viewAll: "Lihat perjalanan kelompok",
    todayTarget: "Perjalanan kelompok hari ini",
    todayTargetHint: "Seberapa jauh kelompokmu dalam bacaan hari ini.",
    todayPassage: "Pasal hari ini",
    membersRead: "anggota sudah baca",
    achieved: (pct: number) => `${pct}% perjalanan`,
    needsReminder: (count: number) =>
      `${count} anggota dapat diberi pengingat`,
    encourageHint: "Dorong dengan hangat — bukan teguran.",
    allDone: "Semua anggota sudah menyelesaikan bacaan hari ini.",
    roleCard: {
      title: "Peran kamu",
      memberHint: "Akses fitur sesuai peran di kelompok.",
      leaderHint: "Dampingi progress anggota dan kirim pengingat bila perlu.",
      watchMembers: "Lihat anggota",
      viewGroup: "Lihat kelompok",
    },
  },

  members: {
    title: "Anggota kelompok",
    titleLeader: "Anggota kelompok",
    subtitle: (group: string) => `Perjalanan bersama di ${group}.`,
    subtitleLeader: (group: string) =>
      `Dampingi perjalanan baca di ${group}.`,
    subtitleMulti: "Lihat perjalanan bacaan anggota kelompokmu.",
    subtitleMultiLeader: "Lihat perjalanan bacaan setiap anggota.",
    backToProfil: "Kembali ke profil",
    backToGroup: "Kembali ke kelompok",
    backToList: "Kembali ke anggota",
    remindShort: "Dorong",
    attentionTitle: "Perlu perhatian",
    attentionDescription: (count: number) =>
      `${count} anggota belum menyelesaikan bacaan hari ini.`,
    listTitle: "Anggota",
    summary: "Perjalanan kelompok",
    summaryHint: "Progress 14 hari terakhir",
    summaryHintLeader: "Progress 14 hari terakhir seluruh anggota",
    viewDetail: "Lihat detail",
    sendReminder: "Kirim pengingat",
    detail: {
      subtitle: "Perjalanan baca dan riwayat per hari.",
      last14: "14 hari terakhir",
      trendSummary: (completed: number, missed: number, pending: number) =>
        `${completed} selesai · ${missed} belum lanjut · ${pending} menunggu (7 hari)`,
      history: "Riwayat bacaan",
      historyHint: "Status baca per hari dalam periode ini.",
      seeMore: (count: number) => `Lihat ${count} lainnya`,
      seeLess: "Lebih sedikit",
      postsTitle: "Timeline & refleksi",
      postsSubtitle: "Postingan, refleksi, dan renungan yang dibagikan.",
      postsEmpty: "Belum ada postingan atau refleksi dari anggota ini.",
    },
    stats: {
      progress: "Progress",
      readProgress: "Progress baca",
      streak: "Beruntun",
      streakDays: (days: number) => `${days} hr`,
      completed: "Sudah baca",
      missed: "Belum lanjut",
      lastRead: (date: string) => `Terakhir baca: ${date}`,
      lastActive: (label: string) => `Terakhir aktif · ${label}`,
      neverRead: "Belum ada bacaan dalam periode ini",
      neverActive: "Belum pernah aktif",
    },
    summaryLabels: {
      avgRead: "Rata-rata baca",
      members: "Anggota",
      readToday: "Baca hari ini",
      pendingMissed: "Belum lanjut",
    },
    legend: {
      completed: "Sudah baca",
      missed: "Belum lanjut",
      pending: "Menunggu",
    },
    todayStatus: {
      completed: "Sudah baca hari ini",
      pending: "Belum baca hari ini",
      missed: "Belum dilanjutkan hari ini",
    },
    dayStatus: {
      completed: "Selesai",
      missed: "Belum lanjut",
      pending: "Menunggu",
    },
  },

  groups: {
    title: "Kelompok",
    subtitle: "Kita sedang menjalani perjalanan ini bersama.",
    leader: (name: string) => `Ketua: ${name}`,
    viewMembers: "Lihat anggota",
    tabOverview: "Ringkasan",
    tabProgress: "Progress",
    tabMembers: "Anggota",
    recentActivity: "Aktivitas terbaru",
    todayRead: "Baca hari ini",
    avg14Days: "Rata-rata bacaan",
    membersNeedAttention: (count: number) =>
      `${count} anggota perlu perhatian hari ini`,
    allOnTrack: "Semua on track hari ini",
    sendReminder: "Kirim pengingat",
    writeReflection: "Tulis refleksi",
    feedActivity: "Aktivitas",
    feedTimeline: "Timeline",
    todayPassage: "Bacaan hari ini",
    attentionCta: "Lihat anggota",
    progressTodaySummary: (done: number, total: number, pct: number) =>
      `Hari ini ${done}/${total} anggota sudah baca (${pct}%)`,
    journeyTitle: "Perjalanan bersama",
    todayParticipation: "Partisipasi hari ini",
    recentReflections: "Renungan terbaru",
    noReflections: "Belum ada renungan kelompok hari ini.",
    timelineTitle: "Timeline kelompok",
    timelineSubtitle:
      "Refleksi dan postingan anggota — saling menguatkan seperti feed bersama.",
    timelineEmpty: "Belum ada postingan di kelompok ini. Mulai bagikan refleksi.",
    timelinePlaceholder: "Bagikan refleksi atau kabar singkat ke kelompok…",
    programLabel: "Program",
    encouragement: "Saling mendukung — tanpa tekanan, tanpa ranking.",
  },

  notes: {
    title: "Renungan",
    subtitle: "Tulis apa yang berbicara padamu — bagikan hanya jika kamu ingin.",
    today: "Renungan hari ini",
    history: "Riwayat renungan",
    updated: (date: string) => `Diperbarui ${date}`,
    prompt: "Apa yang paling berbicara padamu dari bacaan hari ini?",
    promptOptional: "Bagaimana kamu ingin menerapkannya dalam kehidupanmu?",
    placeholder:
      "Apa yang Tuhan taruh di hatimu? Tulis refleksi atau doa di sini…",
    privacy: "Default pribadi. Kamu yang memilih siapa yang dapat membaca.",
    save: "Simpan renungan",
    saved: "Tersimpan",
    visibility: {
      label: "Siapa yang dapat membaca",
      private: "Pribadi",
      privateHint: "Hanya kamu",
      leader: "Ketua saja",
      leaderHint: "Kamu dan ketua kelompok",
      group: "Kelompok",
      groupHint: "Semua anggota kelompok",
    },
    afterComplete: "Bacaan selesai. Luangkan waktu singkat untuk merenung.",
  },

  myReflections: {
    eyebrow: "Catatan pribadi",
    title: "Refleksiku",
    subtitle: "Yang kamu tulis setelah baca — tersimpan di perangkatmu.",
    write: "Tulis refleksi",
    empty: "Belum ada refleksi",
    emptyHint:
      "Setelah baca, catat apa yang berbicara padamu. Nanti muncul di sini.",
  },

  notifications: {
    title: "Notifikasi",
    subtitle: "Pengingat, dorongan, dan kabar dari kelompokmu.",
    empty: "Belum ada notifikasi baru.",
    emptyHint: "Pengingat baca dan dorongan dari ketua akan muncul di sini.",
    emptyFilter: "Tidak ada notifikasi di kategori ini.",
    emptyFilterHint: "Coba pilih kategori lain atau lihat semua notifikasi.",
    filterAll: "Semua",
    filterAria: "Filter kategori notifikasi",
    types: {
      reminder: "Pengingat baca",
      encouragement: "Dorongan",
      announcement: "Pengumuman kelompok",
      reflection: "Renungan baru",
    },
  },

  auth: {
    google: {
      continue: "Lanjutkan dengan Google",
      loading: "Mengalihkan ke Google…",
      divider: "atau",
    },
    login: {
      title: "Masuk",
      description: "Gunakan akun komunitasmu untuk melanjutkan bacaan hari ini.",
      submit: "Masuk",
      loading: "Sedang masuk…",
      error: "Username atau password salah. Silakan coba lagi.",
      rememberMe: "Ingat saya",
      forgotPassword: "Lupa password?",
      noAccount: "Belum punya akun?",
      register: "Daftar",
    },
    forgotPassword: {
      title: "Lupa password",
      description:
        "Masukkan username atau email akunmu. Untuk demo, kamu bisa langsung atur password baru.",
      submit: "Lanjut",
      loading: "Memeriksa akun…",
      backToLogin: "Kembali ke masuk",
      notFound:
        "Jika akun terdaftar, instruksi reset akan dikirim. Coba lagi atau hubungi admin komunitas.",
      resetTitle: "Atur password baru",
      resetDescription: (name: string) =>
        `Akun ${name} ditemukan. Masukkan password baru untuk demo ini.`,
      newPassword: "Password baru",
      confirmPassword: "Ulangi password baru",
      resetSubmit: "Simpan password baru",
      resetLoading: "Menyimpan…",
      mismatch: "Password tidak cocok.",
      tooShort: "Password minimal 6 karakter.",
      success: "Password berhasil diperbarui. Silakan masuk.",
      goLogin: "Masuk sekarang",
    },
    register: {
      title: "Buat akun",
      description: "Isi data singkat, lalu langsung bergabung dengan kelompok.",
      submit: "Buat akun",
      loading: "Membuat akun…",
      error: "Pendaftaran gagal. Periksa email atau coba lagi.",
      hasAccount: "Sudah punya akun?",
      login: "Masuk",
    },
  },

  admin: {
    title: "Panel Admin",
    subtitle: "Pantau kesehatan program — untuk merawat, bukan mengawasi.",
    health: {
      title: "Kesehatan program",
      hint: "Ringkasan partisipasi dan keterlibatan komunitas.",
      participants: "Total peserta",
      activeReaders: "Pembaca aktif",
      completionRate: "Tingkat penyelesaian",
      weeklyActive: "Aktif minggu ini",
      reflections: "Partisipasi renungan",
      groupEngagement: "Keterlibatan kelompok",
    },
    schedule: {
      title: "Tambah bacaan harian",
      description:
        "Lihat seluruh jadwal program, atau tambahkan pasal untuk tanggal tertentu.",
      date: "Tanggal",
      passage: "Pasal Alkitab",
      passagePlaceholder: "Pilih satu atau lebih pasal",
      reflectionPrompt: "Pertanyaan refleksi",
      reflectionPlaceholder:
        "Apa yang paling berbicara padamu dari bacaan hari ini?",
      publish: "Terbitkan ke jadwal",
    },
    groups: {
      title: "Kelola kelompok",
      description: "Buat kelompok dalam program dan tentukan ketuanya.",
      name: "Nama kelompok",
      namePlaceholder: "Kelompok 01",
      leaderEmail: "Email ketua",
      leaderEmailPlaceholder: "ketua@example.com",
      create: "Buat kelompok",
    },
    program: {
      title: "Program baca",
      description:
        "Organisasi → Program → Kelompok. Satu organisasi dapat memiliki banyak program.",
      orgName: "Organisasi",
      orgPlaceholder: "Komunitas Kristen A",
      programName: "Nama program",
      programPlaceholder: "Bible Reading Journey 2027",
    },
  },
} as const;
